-- =========================
-- QS_Darkshore_20_21.lua
-- Converted from TourGuide format on 2025-08-16 22:16:15
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Darkshore_20_21"] = {
  title    = "Darkshore (20-21)",
  next     = "Ashenvale (21-22)",
  nextKey  = "QS_Ashenvale_21_22",
  faction  = "Alliance",
  minLevel = 20,
  maxLevel = 21,
  steps = {
    { type="NOTE", note="You need to be at least level 20 to continue, keep grinding until you reach level 20" },
    { type="ACCEPT", class="Warlock", title="Gakin's Summons", questId=1685, coords={ x=4.5, y=66.21 }, npc = { name="Remen Marcot" }, note="Remen Marcot in Lion's Pride Inn<br/><b>Warlock quest line that will reward you with (spell:712) and Small Soul Pouch (4.50, 66.21)" },
    { type="TURNIN", class="Warlock", title="Gakin's Summons", questId=1685, coords={ x=25.37, y=78.61 }, note="in The Slaughtered Lamb (25.37, 78.61)" },
    { type="TURNIN", class="Warlock", title="Gakin's Summons", questId=1717, coords={ x=25.37, y=78.61 }, note="in The Slaughtered Lamb (25.37, 78.61)" },
    { type="ACCEPT", class="Warlock", title="Devourer of Souls", questId=1716, coords={ x=25.37, y=78.61 }, npc = { name="Gakin" }, note="Gakin the Darkbinder in The Slaughtered Lamb (25.37, 78.61)" },
    { type="TURNIN", class="Warlock", title="Gakin's Summons", questId=1717, coords={ x=25.3, y=78.52 }, npc = { name="Gakin" }, note="Gakin the Darkbinder in The Slaughtered Lamb (25.30, 78.52)" },
    { type="ACCEPT", class="Warlock", title="Devourer of Souls", questId=1716, coords={ x=25.3, y=78.52 }, npc = { name="Gakin" }, note="Gakin the Darkbinder in The Slaughtered Lamb (25.30, 78.52)" },
    { type="TURNIN", class="Warlock", title="Devourer of Souls", questId=1716, coords={ x=49.3, y=57.1 }, npc = { name="Takar" }, note="Takar the Seer in Southern Barrens (49.30, 57.10)" },
    { type="ACCEPT", class="Warlock", title="Heartswood", questId=1738, coords={ x=49.3, y=57.1 }, npc = { name="Takar" }, note="Takar the Seer in Southern Barrens (49.30, 57.10)" },
    { type="COMPLETE", class="Warlock", title="Heartswood", questId=1738, coords={ x=31.5, y=31.44 }, note="Collect the Heartswood from the big tree in The Ruins of Ordil'Aran (31.50, 31.44)" },
    { type="TURNIN", class="Warlock", title="Heartswood", questId=1738, coords={ x=25.28, y=78.5 }, npc = { name="Gakin" }, note="Gakin the Darkbinder in The Slaughtered Lamb (25.28, 78.50)" },
    { type="ACCEPT", class="Warlock", title="The Binding", questId=1739, coords={ x=25.28, y=78.5 }, npc = { name="Gakin" }, note="Gakin the Darkbinder in The Slaughtered Lamb (25.28, 78.50)" },
    { type="COMPLETE", class="Warlock", title="The Binding", questId=1739, coords={ x=25.07, y=77.37 }, note="Using the Heartswood Core, summon and subdue a Summoned Succubus in The Slaughtered Lamb (25.07, 77.37)" },
    { type="TURNIN", class="Warlock", title="The Binding", questId=1739, coords={ x=25.24, y=78.58 }, npc = { name="Gakin" }, note="Gakin the Darkbinder in The Slaughtered Lamb (25.24, 78.58)" },
    { type="NOTE", class="Paladin", race="Dwarf", note="Speak to Brandur Ironhammer and collect Tome of Valor in Hall of Mysteries. This is an optional Paladin quest to unlock (spell:5502) skill and Bastion of Stormwind. Tick to skip(23.12, 6.07)", coords={ x=23.12, y=6.07 } },
    { type="NOTE", class="Paladin", race="Human", note="Speak to Duthorian Rall and collect Tome of Valor in Cathedral of Light. This is an optional Paladin quest to unlock (spell:5502) skill and Bastion of Stormwind. Tick to skip (39.84, 29.86)", coords={ x=39.84, y=29.86 } },
    { type="ACCEPT", class="Paladin", title="The Tome of Valor", questId=1649, note="Use Tome of Valor accept quest" },
    { type="TRAVEL", class="Paladin", coords={ x=39.85, y=29.91 }, note="Travel to Cathedral of Light (39.85, 29.91)" },
    { type="TURNIN", class="Paladin", title="The Tome of Valor", questId=1649, coords={ x=39.85, y=29.91 }, npc = { name="Duthorian Rall" }, note="Duthorian Rall in Cathedral of Light (39.85, 29.91)" },
    { type="ACCEPT", class="Paladin", title="The Tome of Valor", questId=1650, coords={ x=39.85, y=29.91 }, npc = { name="Duthorian Rall" }, note="Duthorian Rall in Cathedral of Light (39.85, 29.91)" },
    { type="TURNIN", class="Paladin", title="The Tome of Valor", questId=1650, coords={ x=38.49, y=82.62 }, npc = { name="Daphne Stilwell" }, note="Daphne Stilwell in The Dagger Hills (38.49, 82.62) (39.92, 86.68) (41.48, 88.85)" },
    { type="ACCEPT", class="Paladin", title="The Tome of Valor", questId=1651, coords={ x=41.27, y=89.08 }, npc = { name="Daphne Stilwell" }, note="Daphne Stilwell in The Dagger Hills (41.27, 89.08)" },
    { type="COMPLETE", class="Paladin", title="The Tome of Valor", questId=1651, coords={ x=42.21, y=88.67 }, note="Defend Daphne Stilwell from the Defias attack in The Dagger Hills. Up to 4 level 17 Defias Raider will attack you at the same time, be ready to use cooldowns and potions if you have any (42.21, 88.67)" },
    { type="TURNIN", class="Paladin", title="The Tome of Valor", questId=1651, coords={ x=41.62, y=88.84 }, npc = { name="Daphne Stilwell" }, note="Daphne Stilwell in The Dagger Hills (41.62, 88.84)" },
    { type="ACCEPT", class="Paladin", title="The Tome of Valor", questId=1652, coords={ x=41.18, y=88.53 }, npc = { name="Daphne Stilwell" }, note="Daphne Stilwell in The Dagger Hills (41.18, 88.53)" },
    { type="TRAVEL", class="Paladin", coords={ x=39.85, y=29.91 }, note="Travel to Cathedral of Light (39.85, 29.91)" },
    { type="TURNIN", class="Paladin", title="The Tome of Valor", questId=1652, coords={ x=39.82, y=29.78 }, npc = { name="Duthorian Rall" }, note="Duthorian Rall in Cathedral of Light - Skip 'The Test of Righteousness' quest line (39.82, 29.78)" },
    { type="TRAVEL", coords={ x=38.49, y=82.62 }, note="Travel to Stormwind City (38.49, 82.62)" },
    { type="NOTE", note="Withdraw Letter to Delgren from the bank. Tick this step (57.00, 72.81)", coords={ x=57.0, y=72.81 } },
    { type="NOTE", note="Withdraw Fandral's Message from the bank. Tick this step (57.00, 72.81)", coords={ x=57.0, y=72.81 } },
    { type="TRAVEL", coords={ x=37.21, y=44.27 }, note="Travel to Auberdine (37.21, 44.27)" },
    { type="ACCEPT", title="WANTED: Murkdeep!", questId=4740, coords={ x=37.21, y=44.27 }, npc = { name="Wanted Poster" }, note="Wanted Poster in Auberdine (37.21, 44.27)" },
    { type="ACCEPT", title="How Big a Threat?", questId=984, coords={ x=39.35, y=43.46 }, npc = { name="Terenthis" }, note="Terenthis in Auberdine (39.35, 43.46)" },
    { type="ACCEPT", title="The Absent Minded Prospector", questId=729, coords={ x=37.48, y=41.85 }, npc = { name="Archaeologist Hollee" }, note="Archaeologist Hollee in Auberdine (37.48, 41.85)" },
    { type="COMPLETE", title="How Big a Threat?", questId=984, coords={ x=39.92, y=53.62 }, note="Find a corrupt furbolg camp in Darkshore, you just need to reach the waypoint to complete the quest (39.92, 53.62)" },
    { type="TURNIN", title="How Big a Threat?", questId=984, coords={ x=39.35, y=43.46 }, npc = { name="Terenthis" }, note="Terenthis in Auberdine (39.35, 43.46)" },
    { type="ACCEPT", title="How Big a Threat?", questId=985, coords={ x=39.35, y=43.46 }, npc = { name="Terenthis" }, note="Terenthis in Auberdine (39.35, 43.46)" },
    { type="ACCEPT", title="Cave Mushrooms", questId=947, coords={ x=37.32, y=43.66 }, npc = { name="Barithras Moonshade" }, note="Barithras Moonshade in Auberdine (37.32, 43.66)" },
    { type="COMPLETE", title="Cave Mushrooms", questId=947, coords={ x=54.26, y=31.83 }, note="Follow the path to the cave guarded by Naga's and collect 5 Scaber Stalk and 1 Death Cap from the ground inside the cave (54.26, 31.83) (54.99, 32.94) (54.96, 33.37) (56, 35)" },
    { type="COMPLETE", title="How Big a Threat?", questId=985, coords={ x=39.0, y=54.0 }, note="Kill 8 Blackwood Pathfinder (39, 54) and 5 Blackwood Windtalker in the furbolg camp (39, 52)" },
    { type="TURNIN", title="Cave Mushrooms", questId=947, coords={ x=37.32, y=43.66 }, npc = { name="Barithras Moonshade" }, note="Barithras Moonshade in Auberdine (37.32, 43.66)" },
    { type="TURNIN", title="How Big a Threat?", questId=985, coords={ x=39.35, y=43.46 }, npc = { name="Terenthis" }, note="Terenthis in Auberdine (39.35, 43.46)" },
    { type="ACCEPT", title="Onu", questId=948, coords={ x=37.32, y=43.66 }, npc = { name="Barithras Moonshade" }, note="Barithras Moonshade in Auberdine (37.32, 43.66)" },
    { type="TRAVEL", coords={ x=43.55, y=76.32 }, note="Travel to Grove of the Ancients (43.55, 76.32)" },
    { type="TURNIN", title="Grove of the Ancients", questId=952, coords={ x=43.55, y=76.37 }, npc = { name="Onu" }, note="Onu in Grove of the Ancients (43.55, 76.37)" },
    { type="TURNIN", title="Onu", questId=948, coords={ x=43.55, y=76.32 }, npc = { name="Onu" }, note="Onu in Grove of the Ancients (43.55, 76.32)" },
    { type="ACCEPT", title="The Master's Glaive", questId=944, coords={ x=43.55, y=76.32 }, npc = { name="Onu" }, note="Onu in Grove of the Ancients (43.55, 76.32)" },
    { type="COMPLETE", title="The Master's Glaive", questId=944, itemId=5251, coords={ x=39.25, y=84.98 }, note="Travel south from the Grove of Ancients into The Master's Glaive until you've completed the quest (39.25, 84.98)" },
    { type="TURNIN", title="The Master's Glaive", questId=944, coords={ x=39.25, y=84.98 }, note="Use Phial of Scrying to summon the Scrying Bowl in The Master's Glaive (39.25, 84.98)" },
    { type="ACCEPT", title="The Twilight Camp", questId=949, coords={ x=39.25, y=84.98 }, note="Use Phial of Scrying to summon the Scrying Bowl in The Master's Glaive (39.25, 84.98)" },
    { type="TURNIN", title="The Twilight Camp", questId=949, coords={ x=38.57, y=86.02 }, npc = { name="Twilight Tome" }, note="Twilight Tome in The Master's Glaive (38.57, 86.02)" },
    { type="NOTE", note="Destroy Phial of Scrying as it is no longer needed" },
    { type="ACCEPT", title="Return to Onu", questId=950, coords={ x=38.57, y=86.02 }, npc = { name="Twilight Tome" }, note="Twilight Tome in The Master's Glaive (38.57, 86.02)" },
    { type="ACCEPT", title="Therylune's Escape", questId=945, coords={ x=38.7, y=87.4 }, npc = { name="Therylune" }, note="Therylune in The Master's Glaive (38.7, 87.4)" },
    { type="COMPLETE", title="Therylune's Escape", questId=945, coords={ x=22.7, y=51.9 }, note="Escort Therylune until she escapes (22.7, 51.9)" },
    { type="NOTE", note="Kill Twilight Disciple or Twilight Thug until you find Book: The Powers Below to begin a quest in The Master's Glaive (39.6, 86.6)", coords={ x=39.6, y=86.6 } },
    { type="ACCEPT", title="The Powers Below", questId=968, note="Use Book: The Powers Below to accept the quest" },
    { type="TURNIN", title="The Absent Minded Prospector", questId=729, coords={ x=35.75, y=83.69 }, npc = { name="Prospector Remtravel" }, note="Prospector Remtravel in Remtravel's Excavation (35.75, 83.69)" },
    { type="ACCEPT", title="The Absent Minded Prospector", questId=731, coords={ x=35.76, y=83.71 }, npc = { name="Prospector Remtravel" }, note="Prospector Remtravel in Remtravel's Excavation (35.76, 83.71)" },
    { type="COMPLETE", title="The Absent Minded Prospector", questId=731, coords={ x=36.0, y=86.0 }, note="Protect Prospector Remtravel as he searches for the mysterious fossil<br/><b>This can be quite difficult to solo, try to clear the mobs in the area before accepting the quest. You can redo the quest if you fail but you need to wait about 5 mins for the quest giver to respawn (36, 86)" },
    { type="COMPLETE", title="WANTED: Murkdeep!", questId=4740, coords={ x=36.55, y=76.53 }, note="Kill murlocs around the area and Murkdeep will eventually appear, kill him complete the quest (36.55, 76.53)" },
    { type="TURNIN", title="Washed Ashore", questId=4681, coords={ x=36.61, y=45.59 }, npc = { name="Gwennyth Bly'Leggonde" }, note="Gwennyth Bly'Leggonde in Auberdine (36.61, 45.59)" },
    { type="ACCEPT", title="Beached Sea Creature", questId=4730, coords={ x=32.66, y=80.89 }, npc = { name="Beached Sea Creature" }, note="Beached Sea Creature in Twilight Shore (32.66, 80.89)" },
    { type="TURNIN", title="Beached Sea Creature", questId=4730, coords={ x=36.61, y=45.59 }, npc = { name="Gwennyth Bly'Leggonde" }, note="Gwennyth Bly'Leggonde in Auberdine (36.61, 45.59)" },
    { type="TURNIN", title="The Absent Minded Prospector", questId=731, coords={ x=37.46, y=41.88 }, npc = { name="Archaeologist Hollee" }, note="Archaeologist Hollee in Auberdine (37.46, 41.88)" },
    { type="TURNIN", title="WANTED: Murkdeep!", questId=4740, coords={ x=37.7, y=43.44 }, npc = { name="Sentinel Glynda Nal'Shea" }, note="Sentinel Glynda Nal'Shea in Auberdine (37.70, 43.44)" },
    { type="TRAVEL", coords={ x=43.55, y=76.32 }, note="Travel to Grove of the Ancients (43.55, 76.32)" },
    { type="TURNIN", title="Return to Onu", questId=950, coords={ x=43.55, y=76.32 }, npc = { name="Onu" }, note="Onu in Grove of the Ancients (43.55, 76.32)" },
    { type="ACCEPT", title="Mathystra Relics", questId=951, coords={ x=43.57, y=76.34 }, npc = { name="Onu" }, note="Onu in Grove of the Ancients (43.57, 76.34)" },
    { type="ACCEPT", title="The Sleeper Has Awakened", questId=5321, coords={ x=44.38, y=76.42 }, npc = { name="Kerlonian Evershade" }, note="Kerlonian Evershade in Grove of the Ancients (44.38, 76.42)" },
    { type="NOTE", note="Collect Horn of Awakening from the chest next to Kerlonian Evershade in Grove of the Ancients (44.37, 76.36)", coords={ x=44.37, y=76.36 } },
    { type="NOTE", note="Kerlonian Evershade will occasionally fall asleep, use the Horn of Awakening to wake him back up" },
    { type="ACCEPT", title="One Shot.  One Kill.", questId=5713, coords={ x=45.8, y=90.2 }, npc = { name="Sentinel Aynasha" }, note="Sentinel Aynasha in Dark Shore (45.8, 90.2)" },
    { type="COMPLETE", title="One Shot.  One Kill.", questId=5713, itemId=13536, coords={ x=45.8, y=90.2 }, note="Protect Sentinel Aynasha until the quest is complete (45.8, 90.2)" },
    { type="COMPLETE", title="The Sleeper Has Awakened", questId=5321, itemId=13536, coords={ x=29.01, y=25.66 }, note="Escort Kerlonian Evershade to Maestra's Post<br/><b>Avoid the main road so you don't get ambushed by 4 mobs (29.01, 25.66) (27.25, 35.62)" },
    { type="TURNIN", title="The Sleeper Has Awakened", questId=5321, coords={ x=27.25, y=35.62 }, npc = { name="Liladris Moonriver" }, note="Liladris Moonriver in Maestra's Post (27.25, 35.62)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
