-- =========================
-- QS_Wetlands_24_27.lua
-- Converted from TourGuide format on 2025-08-16 22:16:17
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Wetlands_24_27"] = {
  title    = "Wetlands (24-27)",
  next     = "Redridge Mountains (27-28)",
  nextKey  = "QS_Redridge_Mountains_27_28",
  faction  = "Alliance",
  minLevel = 24,
  maxLevel = 27,
  steps = {
    { type="TRAVEL", coords={ x=8.31, y=58.54 }, note="Travel to Menethil Harbor (8.31, 58.54)" },
    { type="ACCEPT", title="Claws from the Deep", questId=279, coords={ x=8.31, y=58.54 }, npc = { name="Karl Boran" }, note="Karl Boran in Menethil Harbor (8.31, 58.54)" },
    { type="ACCEPT", title="Young Crocolisk Skins", questId=484, coords={ x=8.51, y=55.81 }, npc = { name="James Halloran" }, note="James Halloran in Menethil Harbor (8.51, 55.81)" },
    { type="ACCEPT", title="The Third Fleet", questId=288, coords={ x=10.91, y=59.53 }, npc = { name="First Mate Fitzsimmons" }, note="First Mate Fitzsimmons in Menethil Harbor (10.91, 59.53)" },
    { type="ACCEPT", title="The Greenwarden", questId=463, coords={ x=10.91, y=59.53 }, npc = { name="First Mate Fitzsimmons" }, note="First Mate Fitzsimmons in Menethil Harbor (10.91, 59.53)" },
    { type="SET_HEARTH", title="The Absent Minded Prospector", coords={ x=10.7, y=60.9 }, npc = { name="Innkeeper Helbrek" }, note="Speak to Innkeeper Helbrek and set hearth at Deepwater Tavern (10.7, 60.9)" },
    { type="NOTE", note="Speak to Innkeeper Helbrek and purchase Flagon of Mead at Deepwater Tavern (10.7, 60.9) for 15 silver", coords={ x=10.7, y=60.9 } },
    { type="TURNIN", title="The Absent Minded Prospector", questId=942, coords={ x=10.81, y=60.41 }, npc = { name="Archaeologist Flagongut" }, note="Archaeologist Flagongut in Deepwater Tavern (10.81, 60.41)" },
    { type="ACCEPT", title="The Absent Minded Prospector", questId=943, coords={ x=10.81, y=60.41 }, npc = { name="Archaeologist Flagongut" }, note="Archaeologist Flagongut in Deepwater Tavern (10.81, 60.41)" },
    { type="TURNIN", title="The Third Fleet", questId=288, coords={ x=10.91, y=59.53 }, npc = { name="First Mate Fitzsimmons" }, note="First Mate Fitzsimmons in Menethil Harbor (10.91, 59.53)" },
    { type="ACCEPT", title="The Cursed Crew", questId=289, coords={ x=10.91, y=59.53 }, npc = { name="First Mate Fitzsimmons" }, note="First Mate Fitzsimmons in Menethil Harbor (10.91, 59.53)" },
    { type="ACCEPT", title="Digging Through the Ooze", questId=470, coords={ x=11.74, y=57.97 }, npc = { name="Sida" }, note="Sida in Menethil Harbor (11.74, 57.97)" },
    { type="ACCEPT", title="Report to Captain Stoutfist", questId=473, npc = { name="Valstag Ironjaw" }, note="Valstag Ironjaw in Menethil Keep (10.0 56.8)" },
    { type="TURNIN", title="Report to Captain Stoutfist", questId=473, coords={ x=9.9, y=57.43 }, npc = { name="Captain Stoutfist" }, note="Captain Stoutfist in Menethil Keep (9.90, 57.43)" },
    { type="ACCEPT", title="War Banners", questId=464, coords={ x=9.9, y=57.43 }, npc = { name="Captain Stoutfist" }, note="Captain Stoutfist in Menethil Keep (9.90, 57.43)" },
    { type="ACCEPT", title="In Search of The Excavation Team", questId=305, coords={ x=11.47, y=52.2 }, npc = { name="Tarrel Rockweaver" }, note="Tarrel Rockweaver in Menethil Harbor (11.47, 52.20)" },
    { type="NOTE", note="Kill Young Wetlands Crocolisk to collect 4 Young Crocolisk Skin" },
    { type="COMPLETE", title="Claws from the Deep", questId=279, coords={ x=17.98, y=40.49 }, note="Kill Gobbler and collect Gobbler's Head in Whelgar's Excavation Site (17.98, 40.49) | Kill Bluegill Murloc in Whelgar's Excavation Site (19.72, 41.08)" },
    { type="ACCEPT", title="Ormer's Revenge", questId=294, coords={ x=38.1, y=50.4 }, npc = { name="Ormer Ironbraid" }, note="Ormer Ironbraid in Whelgar's Excavation Site (38.1, 50.4)" },
    { type="TURNIN", title="In Search of The Excavation Team", questId=305, coords={ x=38.89, y=52.34 }, npc = { name="Merrin Rockweaver" }, note="Merrin Rockweaver in Whelgar's Excavation Site (38.89, 52.34)" },
    { type="ACCEPT", title="In Search of The Excavation Team", questId=306, coords={ x=38.89, y=52.34 }, npc = { name="Merrin Rockweaver" }, note="Merrin Rockweaver in Whelgar's Excavation Site (38.89, 52.34)" },
    { type="NOTE", note="Collect Flagongut's Fossil from the chest near Merrin Rockweaver (38.8, 52.2)", coords={ x=38.8, y=52.2 } },
    { type="TRAVEL", coords={ x=36.97, y=47.26 }, note="Travel to Black Channel Marsh (36.97, 47.26) (33.95, 40.93) (23.38, 53.52)" },
    { type="NOTE", note="Kill any Black Ooze to collect Sida's Bag" },
    { type="COMPLETE", title="Ormer's Revenge", questId=294, coords={ x=23.38, y=53.52 }, note="Kill 10 Mottled Screecher and 10 Mottled Raptor which are found around Black Channel Marsh (23.38, 53.52)" },
    { type="COMPLETE", title="The Absent Minded Prospector", questId=943, coords={ x=23.38, y=53.52 }, note="Kill Mottled Raptor and until you collect Stone of Relu (23.38, 53.52)" },
    { type="TRAVEL", coords={ x=36.85, y=43.08 }, note="Travel to Whelgar's Excavation Site (36.85, 43.08)" },
    { type="TURNIN", title="Ormer's Revenge", questId=294, coords={ x=36.85, y=43.08 }, npc = { name="Ormer Ironbraid" }, note="Ormer Ironbraid in Whelgar's Excavation Site (36.85, 43.08) (38.1, 50.4)" },
    { type="ACCEPT", title="Ormer's Revenge", questId=295, coords={ x=38.1, y=50.4 }, npc = { name="Ormer Ironbraid" }, note="Ormer Ironbraid in Whelgar's Excavation Site (38.1, 50.4)" },
    { type="TRAVEL", coords={ x=49.93, y=39.38 }, note="Travel to The Green Belt (49.93, 39.38)" },
    { type="ACCEPT", title="Daily Delivery", questId=469, coords={ x=49.93, y=39.38 }, npc = { name="Einar Stonegrip" }, note="Einar Stonegrip in The Green Belt (49.93, 39.38)" },
    { type="TURNIN", title="The Greenwarden", questId=463, coords={ x=56.24, y=40.3 }, npc = { name="Rethiel" }, note="Rethiel the Greenwarden in The Green Belt (56.24, 40.30)" },
    { type="ACCEPT", title="Tramping Paws", questId=276, coords={ x=56.24, y=40.3 }, npc = { name="Rethiel" }, note="Rethiel the Greenwarden in The Green Belt (56.24, 40.30)" },
    { type="COMPLETE", title="Tramping Paws", questId=276, coords={ x=62.0, y=66.0 }, note="Kill 15 Mosshide Gnoll and 10 Mosshide Mongrel which are found to the South (62, 66)" },
    { type="TURNIN", title="Tramping Paws", questId=276, coords={ x=56.24, y=40.3 }, npc = { name="Rethiel" }, note="Rethiel the Greenwarden in The Green Belt (56.24, 40.30)" },
    { type="ACCEPT", title="Fire Taboo", questId=277, coords={ x=56.24, y=40.3 }, npc = { name="Rethiel" }, note="Rethiel the Greenwarden in The Green Belt (56.24, 40.30)" },
    { type="COMPLETE", title="Young Crocolisk Skins", questId=484, coords={ x=51.0, y=36.0 }, note="Kill Young Wetlands Crocolisk and collect 4 Young Crocolisk Skin in The Green Belt (51, 36)" },
    { type="COMPLETE", title="Digging Through the Ooze", questId=470, note="Kill Black Ooze to collect Sida's Bag in The Green Belt, 25.2)" },
    { type="TRAVEL", coords={ x=38.0, y=31.0 }, note="Travel to The Green Belt (38, 31)" },
    { type="COMPLETE", title="Fire Taboo", questId=277, coords={ x=38.0, y=31.0 }, note="Kill any Mosshide mobs and collect 9 Crude Flint in The Green Belt (38, 31)" },
    { type="TURNIN", title="Fire Taboo", questId=277, coords={ x=56.24, y=40.3 }, npc = { name="Rethiel" }, note="Rethiel the Greenwarden in The Green Belt (56.24, 40.30)" },
    { type="ACCEPT", title="Blisters on The Land", questId=275, coords={ x=56.24, y=40.3 }, npc = { name="Rethiel" }, note="Rethiel the Greenwarden in The Green Belt (56.24, 40.30)" },
    { type="TRAVEL", coords={ x=8.31, y=58.54 }, note="Travel to Menethil Harbor (8.31, 58.54)" },
    { type="TURNIN", title="The Absent Minded Prospector", questId=943, coords={ x=10.81, y=60.41 }, npc = { name="Archaeologist Flagongut" }, note="Archaeologist Flagongut in Deepwater Tavern (10.81, 60.41)" },
    { type="TURNIN", title="Claws from the Deep", questId=279, coords={ x=8.31, y=58.54 }, npc = { name="Karl Boran" }, note="Karl Boran in Menethil Harbor (8.31, 58.54)" },
    { type="ACCEPT", title="Reclaiming Goods", questId=281, coords={ x=8.31, y=58.54 }, npc = { name="Karl Boran" }, note="Karl Boran in Menethil Harbor (8.31, 58.54)" },
    { type="TURNIN", title="Young Crocolisk Skins", questId=484, coords={ x=8.51, y=55.81 }, npc = { name="James Halloran" }, note="James Halloran in Menethil Harbor (8.51, 55.81)" },
    { type="TURNIN", title="Daily Delivery", questId=469, coords={ x=8.51, y=55.81 }, npc = { name="James Halloran" }, note="James Halloran in Menethil Harbor (8.51, 55.81)" },
    { type="ACCEPT", title="Apprentice's Duties", questId=471, coords={ x=8.51, y=55.81 }, npc = { name="James Halloran" }, note="James Halloran in Menethil Harbor (8.51, 55.81)" },
    { type="TURNIN", title="Digging Through the Ooze", questId=470, coords={ x=11.74, y=57.97 }, npc = { name="Sida" }, note="Sida in Menethil Harbor (11.74, 57.97)" },
    { type="TURNIN", title="In Search of The Excavation Team", questId=306, coords={ x=11.47, y=52.2 }, npc = { name="Tarrel Rockweaver" }, note="Tarrel Rockweaver in Menethil Harbor (11.47, 52.20)" },
    { type="NOTE", note="Kill any Fen Creeper, they are stealth usually found near the water stream" },
    { type="TURNIN", title="Reclaiming Goods", questId=281, coords={ x=13.48, y=41.46 }, npc = { name="Damaged Crate" }, note="Damaged Crate in Bluegill Marsh (13.48, 41.46)" },
    { type="ACCEPT", title="The Search Continues", questId=284, coords={ x=13.48, y=41.46 }, npc = { name="Guard Thomas" }, note="Guard Thomas in Bluegill Marsh (13.48, 41.46)" },
    { type="TURNIN", title="The Search Continues", questId=284, coords={ x=13.59, y=38.08 }, npc = { name="Sealed Barrel" }, note="Sealed Barrel in Bluegill Marsh (13.59, 38.08)" },
    { type="ACCEPT", title="Search More Hovels", questId=285, coords={ x=13.59, y=38.08 }, npc = { name="Sealed Barrel" }, note="Sealed Barrel in Bluegill Marsh (13.59, 38.08)" },
    { type="TURNIN", title="Search More Hovels", questId=285, coords={ x=13.88, y=34.91 }, npc = { name="Half-buried Barrel" }, note="Half-buried Barrel in Bluegill Marsh (13.88, 34.91)" },
    { type="ACCEPT", title="Return the Statuette", questId=286, coords={ x=13.88, y=34.91 }, npc = { name="Half-buried Barrel" }, note="Half-buried Barrel in Bluegill Marsh (13.88, 34.91)" },
    { type="COMPLETE", title="Apprentice's Duties", questId=471, coords={ x=17.76, y=27.68 }, note="Kill Giant Wetlands Crocolisk and collect 6 Giant Crocolisk Skin in Sundown Marsh (17.76, 27.68) (22.98, 22.97)" },
    { type="COMPLETE", title="Blisters on The Land", questId=275, coords={ x=17.76, y=27.68 }, note="Kill 12 Fen Creeper which can be found stealth around in the shallow waters marsh stream. Grind your way towards the quest turnin, you can find more Fen Creeper near the quest giver (17.76, 27.68) (56.24, 40.30)" },
    { type="TURNIN", title="Blisters on The Land", questId=275, coords={ x=56.24, y=40.3 }, npc = { name="Rethiel" }, note="Rethiel the Greenwarden in The Green Belt (56.24, 40.30)" },
    { type="TRAVEL", coords={ x=36.85, y=43.08 }, note="Travel to Whelgar's Excavation Site (36.85, 43.08)" },
    { type="ACCEPT", title="Uncovering the Past", questId=299, coords={ x=36.85, y=43.08 }, npc = { name="Prospector Whelgar" }, note="Prospector Whelgar in Whelgar's Excavation Site (36.85, 43.08) (38.8, 52.3)" },
    { type="NOTE", note="Click on Dirt Pile to collect Neru Fragment in Whelgar's Excavation Site (36.5, 42.11)", coords={ x=36.5, y=42.11 } },
    { type="NOTE", note="Click on the Vase to collect Golm Fragment in Whelgar's Excavation Site (35.1, 44.1)", coords={ x=35.1, y=44.1 } },
    { type="NOTE", note="Click on the Ancient Relic to collect Modr Fragment in Whelgar's Excavation Site (34.4, 44.3)", coords={ x=34.4, y=44.3 } },
    { type="NOTE", note="Click on Ancient Relic to collect Ados Fragment in Whelgar's Excavation Site (32.28, 48.58)", coords={ x=32.28, y=48.58 } },
    { type="COMPLETE", title="Ormer's Revenge", questId=295, coords={ x=34.0, y=42.0 }, note="Kill 10 Mottled Scytheclaw and 10 Mottled Razormaw which are found inside Whelgar's Excavation Site (34, 42)" },
    { type="TURNIN", title="Ormer's Revenge", questId=295, coords={ x=38.1, y=50.4 }, npc = { name="Ormer Ironbraid" }, note="Ormer Ironbraid in Whelgar's Excavation Site (38.1, 50.4)" },
    { type="ACCEPT", title="Ormer's Revenge", questId=296, coords={ x=38.1, y=50.4 }, npc = { name="Ormer Ironbraid" }, note="Ormer Ironbraid in Whelgar's Excavation Site (38.1, 50.4)" },
    { type="COMPLETE", title="Ormer's Revenge", questId=296, coords={ x=31.0, y=50.0 }, note="Find and kill Sarltooth who is found on top of the hill in the Excavation Site to collect Sarltooth's Talon (31, 50)" },
    { type="TURNIN", title="Uncovering the Past", questId=299, coords={ x=36.85, y=43.08 }, npc = { name="Prospector Whelgar" }, note="Prospector Whelgar in Whelgar's Excavation Site (36.85, 43.08) (38.8, 52.3)" },
    { type="TURNIN", title="Ormer's Revenge", questId=296, coords={ x=38.1, y=50.4 }, npc = { name="Ormer Ironbraid" }, note="Ormer Ironbraid in Whelgar's Excavation Site (38.1, 50.4)" },
    { type="TRAVEL", coords={ x=44.0, y=44.0 }, note="Travel to Angerfang Encampment (44, 44) (41.22, 46.17)" },
    { type="COMPLETE", title="War Banners", questId=464, coords={ x=44.0, y=44.0 }, note="Kill Dragonmaw Swamprunner, Dragonmaw Bonewarder and Dragonmaw Raider and collect 8 Dragonmaw War Banner in Angerfang Encampment (44, 44) (41.22, 46.17)" },
    { type="TRAVEL", coords={ x=10.91, y=59.53 }, note="Travel to Menethil Harbor (10.91, 59.53)" },
    { type="TURNIN", title="War Banners", questId=464, coords={ x=9.9, y=57.43 }, npc = { name="Captain Stoutfist" }, note="Captain Stoutfist in Menethil Keep (9.90, 57.43)" },
    { type="ACCEPT", title="Nek'rosh's Gambit", questId=465, coords={ x=9.9, y=57.43 }, npc = { name="Captain Stoutfist" }, note="Captain Stoutfist in Menethil Keep (9.90, 57.43)" },
    { type="TURNIN", title="Apprentice's Duties", questId=471, coords={ x=8.51, y=55.81 }, npc = { name="James Halloran" }, note="James Halloran in Menethil Harbor (8.51, 55.81)" },
    { type="TURNIN", title="Return the Statuette", questId=286, coords={ x=8.31, y=58.54 }, npc = { name="Karl Boran" }, note="Karl Boran in Menethil Harbor (8.31, 58.54)" },
    { type="TRAVEL", coords={ x=13.91, y=31.03 }, note="Travel to The Lost Fleet (13.91, 31.03)" },
    { type="COMPLETE", title="The Cursed Crew", questId=289, coords={ x=13.91, y=31.03 }, note="Collect Snellig's Snuffbox in The Lost Fleet (13.91, 31.03) | Kill 13 Cursed Sailor and 5 Cursed Marine which are found around the shipwreck (13, 27) (14, 30)" },
    { type="TURNIN", title="The Cursed Crew", questId=289, coords={ x=10.91, y=59.53 }, npc = { name="First Mate Fitzsimmons" }, note="First Mate Fitzsimmons in Menethil Harbor (10.91, 59.53)" },
    { type="ACCEPT", title="Lifting the Curse", questId=290, coords={ x=10.91, y=59.53 }, npc = { name="First Mate Fitzsimmons" }, note="First Mate Fitzsimmons in Menethil Harbor (10.91, 59.53)" },
    { type="TRAVEL", coords={ x=55.88, y=47.87 }, note="Travel to Ironforge (55.88, 47.87)" },
    { type="NOTE", note="Store Dwarven Tinder to the bank (35.48, 60.70)", coords={ x=35.48, y=60.7 } },
    { type="NOTE", note="Withdraw Book: The Powers Below from the bank. Tick this step (35.48, 60.70)", coords={ x=35.48, y=60.7 } },
    { type="NOTE", note="Withdraw Bronze Tube from the bank, or purchase from the Auction House. Tick this step (35.48, 60.70)", coords={ x=35.48, y=60.7 } },
    { type="NOTE", note="Ineptitude + Chemicals = Fun", coords={ x=24.2, y=74.4 } },
    { type="TURNIN", title="An Old Colleague", questId=1072, coords={ x=71.8, y=51.4 }, npc = { name="Lomac Gearstrip" }, note="Lomac Gearstrip in Tinker Town (71.8, 51.4)" },
    { type="ACCEPT", title="Ineptitude + Chemicals = Fun", questId=1073, coords={ x=71.8, y=51.4 }, npc = { name="Lomac Gearstrip" }, note="Lomac Gearstrip in Tinker Town (71.8, 51.4)" },
    { type="NOTE", note="Buy 4 Minor Mana Potion and 2 Elixir of Minor Fortitude from the Auction House, skip the quest if items are too expensive for you or not available (24.2, 74.4)", coords={ x=24.2, y=74.4 } },
    { type="TURNIN", title="Ineptitude + Chemicals = Fun", questId=1073, coords={ x=71.8, y=51.4 }, npc = { name="Lomac Gearstrip" }, note="Lomac Gearstrip in Tinker Town (71.8, 51.4)" },
    { type="TURNIN", title="The Powers Below", questId=968, coords={ x=50.8, y=6.0 }, npc = { name="Gerrig Bonegrip" }, note="Gerrig Bonegrip in The Great Forge (50.8, 6.0)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
