-- =========================
-- QS_Hillsbrad_Foothills_31_32.lua
-- Converted from TourGuide format on 2025-08-16 22:16:18
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Hillsbrad_Foothills_31_32"] = {
  title    = "Hillsbrad Foothills (31-32)",
  next     = "Stranglethorn (32-33)",
  nextKey  = "QS_Stranglethorn_32_33",
  faction  = "Alliance",
  minLevel = 31,
  maxLevel = 32,
  steps = {
    { type="TRAVEL", coords={ x=9.9, y=57.45 }, note="Travel to Menethil Keep (9.90, 57.45)" },
    { type="ACCEPT", title="Fall of Dun Modr", questId=472, coords={ x=10.83, y=55.85 }, npc = { name="Harlo Barnaby" }, note="Harlo Barnaby in Menethil Harbor (10.83, 55.85)" },
    { type="TRAVEL", coords={ x=49.92, y=18.23 }, note="Travel to Dun Modr (49.92, 18.23)" },
    { type="TURNIN", title="Fall of Dun Modr", questId=472, coords={ x=49.92, y=18.23 }, npc = { name="Longbraid" }, note="Longbraid the Grim in Dun Modr (49.92, 18.23)" },
    { type="ACCEPT", title="The Thandol Span", questId=631, coords={ x=49.92, y=18.23 }, npc = { name="Longbraid" }, note="Longbraid the Grim in Dun Modr (49.92, 18.23)" },
    { type="TURNIN", title="The Thandol Span", questId=631, coords={ x=45.66, y=93.08 }, npc = { name="Ebenezer Rustlocke's Corpse" }, note="Ebenezer Rustlocke's Corpse in Thandol Span (45.66, 93.08) head down the stairs to the right" },
    { type="ACCEPT", title="The Thandol Span", questId=632, coords={ x=45.66, y=93.08 }, npc = { name="Ebenezer Rustlocke's Corpse" }, note="Ebenezer Rustlocke's Corpse in Thandol Span (45.66, 93.08)" },
    { type="TURNIN", title="The Thandol Span", questId=632, coords={ x=49.91, y=18.2 }, npc = { name="Rhag Garmason" }, note="Rhag Garmason in Dun Modr (49.91, 18.20)" },
    { type="ACCEPT", title="The Thandol Span", questId=633, coords={ x=49.91, y=18.2 }, npc = { name="Rhag Garmason" }, note="Rhag Garmason in Dun Modr (49.91, 18.20)" },
    { type="COMPLETE", title="The Thandol Span", questId=633, coords={ x=45.64, y=88.21 }, note="Destroy the Cache of Explosives. Found across the small bridge to the east (45.64, 88.21) (48.71, 87.98)" },
    { type="TURNIN", title="The Thandol Span", questId=633, coords={ x=49.91, y=18.2 }, npc = { name="Rhag Garmason" }, note="Rhag Garmason in Dun Modr (49.91, 18.20)" },
    { type="ACCEPT", title="Plea To The Alliance", questId=634, coords={ x=49.91, y=18.2 }, npc = { name="Rhag Garmason" }, note="Rhag Garmason in Dun Modr (49.91, 18.20)" },
    { type="ACCEPT", title="MacKreel's Moonshine", questId=647, coords={ x=43.13, y=91.19 }, npc = { name="Foggy MacKreel" }, note="Foggy MacKreel in Thandol Span. You will need to jump across, you can get back up from the path north east if you fall (43.13, 91.19) (43.25, 92.60)" },
    { type="NOTE", note="MacKreel's Moonshine is a timed quest, you have 15 mins to complete the run, follow the waypoint carefully and avoid combat. Tick this step" },
    { type="TRAVEL", coords={ x=48.32, y=88.08 }, note="Follow the waypoint to go back up the hill and run to Refuge Pointe quickly as this is a timed quest (48.32, 88.08) (45.89, 88.13) (45.23, 59.24) (44.43, 48.70)" },
    { type="TURNIN", title="Plea To The Alliance", questId=634, coords={ x=45.85, y=47.59 }, npc = { name="Captain Nials" }, note="Captain Nials in Refuge Pointe (45.85, 47.59)" },
    { type="FLIGHTPATH", npc = { name="Cedrik Prose" }, coords={ x=45.76, y=46.13 }, note="Speak to Cedrik Prose and grab flight path for Refuge Pointe (45.76, 46.13)" },
    { type="TRAVEL", coords={ x=52.14, y=58.71 }, note="Travel to Southshore (52.14, 58.71)" },
    { type="TURNIN", title="Southshore", questId=538, coords={ x=50.56, y=57.13 }, npc = { name="Loremaster Dibbs" }, note="Loremaster Dibbs in Southshore (50.56, 57.13)" },
    { type="ACCEPT", title="Preserving Knowledge", questId=540, coords={ x=50.56, y=57.13 }, npc = { name="Loremaster Dibbs" }, note="Loremaster Dibbs in Southshore (50.56, 57.13)" },
    { type="TURNIN", title="MacKreel's Moonshine", questId=647, coords={ x=52.14, y=58.71 }, npc = { name="Brewmeister Bilger" }, note="Brewmeister Bilger in Southshore (52.14, 58.71)" },
    { type="SET_HEARTH", title="Southshore", coords={ x=51.1, y=58.9 }, npc = { name="Innkeeper Anderson" }, note="Speak to Innkeeper Anderson and set hearth in Southshore (51.1, 58.9)" },
    { type="ACCEPT", title="Soothing Turtle Bisque", questId=555, coords={ x=51.67, y=58.32 }, npc = { name="Chef Jessen" }, note="Chef Jessen in Southshore (51.67, 58.32)" },
    { type="ACCEPT", title="Down the Coast", questId=536, coords={ x=51.45, y=58.48 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.45, 58.48)" },
    { type="ACCEPT", title="Syndicate Assassins", questId=505, coords={ x=48.15, y=59.27 }, npc = { name="Magistrate Henry Maleb" }, note="Magistrate Henry Maleb in Southshore (48.15, 59.27)" },
    { type="ACCEPT", title="Costly Menace", questId=564, coords={ x=52.35, y=56.09 }, npc = { name="Darren Malvew" }, note="Darren Malvew in Southshore (52.35, 56.09)" },
    { type="FLIGHTPATH", npc = { name="Darla Harris" }, coords={ x=49.34, y=52.32 }, note="Speak to Darla Harris and grab flight path for Southshore (49.34, 52.32)" },
    { type="COMPLETE", title="Down the Coast", questId=536, coords={ x=44.0, y=67.0 }, note="Kill 10 Torn Fin Tidehunter and 10 Torn Fin Oracle which can be found along the coast in Western Strand (44, 67)" },
    { type="TURNIN", title="Down the Coast", questId=536, coords={ x=51.43, y=58.35 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.43, 58.35)" },
    { type="ACCEPT", title="Farren's Proof", questId=559, coords={ x=51.43, y=58.35 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.43, 58.35)" },
    { type="COMPLETE", title="Farren's Proof", questId=559, coords={ x=44.0, y=67.0 }, note="Collect 10 Murloc Head from the murlocs found on the Western Strand (44, 67)" },
    { type="TURNIN", title="Farren's Proof", questId=559, coords={ x=51.43, y=58.35 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.43, 58.35)" },
    { type="ACCEPT", title="Farren's Proof", questId=560, coords={ x=51.43, y=58.35 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.43, 58.35)" },
    { type="TURNIN", title="Farren's Proof", questId=560, coords={ x=49.47, y=58.7 }, npc = { name="Marshal Redpath" }, note="Marshal Redpath in Southshore (49.47, 58.70)" },
    { type="ACCEPT", title="Farren's Proof", questId=561, coords={ x=49.47, y=58.7 }, npc = { name="Marshal Redpath" }, note="Marshal Redpath in Southshore (49.47, 58.70)" },
    { type="TURNIN", title="Farren's Proof", questId=561, coords={ x=51.43, y=58.35 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.43, 58.35)" },
    { type="ACCEPT", title="Stormwind Ho!", questId=562, coords={ x=51.43, y=58.35 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.43, 58.35)" },
    { type="COMPLETE", title="Stormwind Ho!", questId=562, coords={ x=56.0, y=65.0 }, note="Kill 10 Daggerspine Shorehunter and 10 Daggerspine Siren in Eastern Strand (56, 65)" },
    { type="TURNIN", title="Stormwind Ho!", questId=562, coords={ x=51.43, y=58.35 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.43, 58.35)" },
    { type="ACCEPT", title="Reassignment", questId=563, coords={ x=51.43, y=58.35 }, npc = { name="Lieutenant Farren Orinelle" }, note="Lieutenant Farren Orinelle in Southshore (51.43, 58.35)" },
    { type="COMPLETE", title="Soothing Turtle Bisque", questId=555, coords={ x=55.79, y=54.39 }, note="Kill Snapjaw along the river and collect 10 Turtle Meat move follow the river north (55.79, 54.39) (64.0, 40.0) (68.6, 28.2)" },
    { type="TRAVEL", coords={ x=58.3, y=67.8 }, note="Travel to Sofera's Naze (58.3, 67.8)" },
    { type="ACCEPT", title="Encrypted Letter", questId=511, coords={ x=58.3, y=67.8 }, npc = { name="Syndicate Documents" }, note="Syndicate Documents in Sofera's Naze (58.3, 67.8)" },
    { type="ACCEPT", title="Foreboding Plans", questId=510, coords={ x=58.3, y=67.8 }, npc = { name="Syndicate Documents" }, note="Syndicate Documents in Sofera's Naze (58.3, 67.8)" },
    { type="COMPLETE", title="Syndicate Assassins", questId=505, coords={ x=57.0, y=66.0 }, note="Kill 12 Syndicate Footpad and 8 Syndicate Thief which can be found at the Camps before entering Alterac Mountains (57, 66) (48, 77)" },
    { type="COMPLETE", title="Costly Menace", questId=564, coords={ x=43.0, y=80.0 }, note="Kill 8 Mountain Lion and 10 Hulking Mountain Lion in The Headland (43, 80)" },
    { type="TRAVEL", coords={ x=49.0, y=55.1 }, note="Travel or Hearthstone back to Southshore (49.0, 55.1)" },
    { type="NOTE", note="Buy Fine Thread from Micha Yance in Southshore (49.0, 55.1)", coords={ x=49.0, y=55.1 } },
    { type="NOTE", note="Buy Soothing Spices from Micha Yance in Southshore (49.0, 55.1)", coords={ x=49.0, y=55.1 } },
    { type="TURNIN", title="Encrypted Letter", questId=511, coords={ x=50.6, y=57.1 }, npc = { name="Loremaster Dibbs" }, note="Loremaster Dibbs in Southshore (50.6, 57.1)" },
    { type="ACCEPT", title="Letter to Stormpike", questId=514, coords={ x=50.0, y=57.0 }, npc = { name="Loremaster Dibbs" }, note="Loremaster Dibbs in Southshore (50, 57)" },
    { type="TURNIN", title="Syndicate Assassins", questId=505, coords={ x=48.14, y=59.13 }, npc = { name="Magistrate Henry Maleb" }, note="Magistrate Henry Maleb in Southshore (48.14, 59.13)" },
    { type="TURNIN", title="Foreboding Plans", questId=510, coords={ x=48.14, y=59.13 }, npc = { name="Magistrate Henry Maleb" }, note="Magistrate Henry Maleb in Southshore (48.14, 59.13)" },
    { type="TURNIN", title="Soothing Turtle Bisque", questId=555, coords={ x=51.84, y=58.68 }, npc = { name="Chef Jessen" }, note="Chef Jessen in Southshore (51.84, 58.68)" },
    { type="TURNIN", title="Costly Menace", questId=564, coords={ x=52.43, y=55.97 }, npc = { name="Darren Malvew" }, note="Darren Malvew in Southshore (52.43, 55.97)" },
    { type="NOTE", note="Destroy Syndicate Missive as it is not used for anything" },
    { type="TRAVEL", coords={ x=45.83, y=47.57 }, note="Travel to Refuge Pointe (45.83, 47.57)" },
    { type="ACCEPT", title="Northfold Manor", questId=681, coords={ x=45.84, y=47.5 }, npc = { name="Captain Nials" }, note="Captain Nials in Refuge Pointe (45.84, 47.50)" },
    { type="COMPLETE", title="Northfold Manor", questId=681, coords={ x=32.74, y=28.63 }, note="Kill 10 Syndicate Highwayman and 6 Syndicate Mercenary in Northfold Manor. Syndicate Highwayman are stealth look for them carefully (32.74, 28.63)" },
    { type="TRAVEL", coords={ x=45.83, y=47.57 }, note="Travel to Refuge Pointe (45.83, 47.57)" },
    { type="TURNIN", title="Northfold Manor", questId=681, coords={ x=45.84, y=47.5 }, npc = { name="Captain Nials" }, note="Captain Nials in Refuge Pointe (45.84, 47.50)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
