-- =========================
-- QS_Stranglethorn_39_40.lua
-- Converted from TourGuide format on 2025-08-16 22:16:21
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Stranglethorn_39_40"] = {
  title    = "Stranglethorn (39-40)",
  next     = "Badlands (40-41)",
  nextKey  = "QS_Badlands_40_41",
  faction  = "Alliance",
  minLevel = 39,
  maxLevel = 40,
  steps = {
    { type="TRAVEL", coords={ x=28.08, y=76.19 }, note="Travel to Booty Bay (28.08, 76.19)" },
    { type="NOTE", note="Withdraw Sample Elven Gem from the bank. Tick this step (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=595, coords={ x=28.08, y=76.19 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.19)" },
    { type="ACCEPT", title="Scaring Shaky", questId=606, coords={ x=27.79, y=77.08 }, npc = { name="MacKinley" }, note="\"Sea Wolf\" MacKinley in Booty Bay (27.79, 77.08)" },
    { type="ACCEPT", title="Venture Company Mining", questId=600, coords={ x=27.13, y=77.3 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.13, 77.30)" },
    { type="TURNIN", title="The Rumormonger", questId=1115, coords={ x=26.95, y=77.22 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern (26.95, 77.22)" },
    { type="ACCEPT", title="Dream Dust in the Swamp", questId=1116, coords={ x=26.95, y=77.22 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern (26.95, 77.22)" },
    { type="ACCEPT", title="Skullsplitter Tusks", questId=209, coords={ x=26.99, y=77.13 }, npc = { name="Kebok" }, note="Kebok in The Salty Sailor Tavern (26.99, 77.13)" },
    { type="SET_HEARTH", title="Water Elementals", coords={ x=27.0, y=77.2 }, npc = { name="Innkeeper Skindle" }, note="Speak to Innkeeper Skindle and set hearth at The Salty Sailor Tavern (27.0, 77.2)" },
    { type="TURNIN", title="Sunken Treasure", questId=669, coords={ x=27.17, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.17, 77.00)" },
    { type="ACCEPT", title="Sunken Treasure", questId=670, coords={ x=27.17, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.17, 77.00)" },
    { type="ACCEPT", title="Water Elementals", questId=601, coords={ x=27.22, y=76.87 }, npc = { name="Baron Revilgaz" }, note="Baron Revilgaz in Booty Bay (27.22, 76.87)" },
    { type="NOTE", note="Store Seaforium Booster to the bank (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Store Elixir of Fortitude to the bank (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="TRAVEL", coords={ x=27.98, y=73.57 }, note="Travel to Mistvale Valley (27.98, 73.57) (29.69, 72.34) (33.03, 65.66)" },
    { type="COMPLETE", title="Scaring Shaky", questId=606, coords={ x=33.03, y=65.66 }, note="Kill Elder Mistvale Gorilla and collect 5 Mistvale Giblets in Mistvale Valley (33.03, 65.66)" },
    { type="TRAVEL", note="Travel to Stranglethorn Vale" },
    { type="COMPLETE", title="Venture Company Mining", questId=600, coords={ x=40.14, y=42.57 }, note="Kill Venture Co. Surveyor or Venture Co. Strip Miner and collect 10 Singing Blue Crystal. You can skip this for now if you find it too difficult (40.14, 42.57) (41.72, 44.57)" },
    { type="TRAVEL", note="Travel to Stranglethorn Vale" },
    { type="COMPLETE", title="Raptor Mastery", questId=196, coords={ x=31.0, y=42.81 }, note="Kill 10 Jungle Stalker near Gurubashi Arena (31.00, 42.81)" },
    { type="TRAVEL", note="Travel to Stranglethorn Vale" },
    { type="COMPLETE", title="Some Assembly Required", questId=577, coords={ x=40.75, y=24.67 }, note="Kill Snapjaw Crocolisk and collect 5 Snapjaw Crocolisk Skin along the river (40.75, 24.67)" },
    { type="TRAVEL", coords={ x=42.17, y=36.16 }, note="Travel to Ziata'jai Ruins (42.17, 36.16)" },
    { type="COMPLETE", title="Skullsplitter Tusks", questId=209, coords={ x=45.72, y=42.19 }, note="Kill Trolls and collect 18 Skullsplitter Tusk in Ziata'jai Ruins and Ruins of Zul'Mamwe. Stick to this area for the lower level trolls (45.72, 42.19) (44.86, 40.70)" },
    { type="COMPLETE", title="Panther Mastery", questId=193, coords={ x=49.52, y=23.82 }, note="Kill Bhag'thera in Stranglethorn Vale. He's stealth, level 40 elite and can be soloed (49.52, 23.82)" },
    { type="TRAVEL", coords={ x=35.65, y=10.79 }, note="Travel to Nesingwary's Expedition (35.65, 10.79)" },
    { type="TURNIN", title="Raptor Mastery", questId=196, coords={ x=35.65, y=10.79 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.79)" },
    { type="ACCEPT", title="Raptor Mastery", questId=197, coords={ x=35.65, y=10.79 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.79)" },
    { type="TURNIN", title="Panther Mastery", questId=193, coords={ x=35.55, y=10.54 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.55, 10.54)" },
    { type="TRAVEL", coords={ x=27.43, y=19.73 }, note="Travel to The Savage Coast (27.43, 19.73)" },
    { type="COMPLETE", title="Water Elementals", questId=601, coords={ x=27.43, y=19.73 }, note="Kill Lesser Water Elemental and collect 6 Water Elemental Bracers in The Savage Coast (27.43, 19.73)(21.08, 23.20)" },
    { type="TRAVEL", coords={ x=27.2, y=76.9 }, note="Travel or Hearthstone to Booty Bay (27.20, 76.90)" },
    { type="TURNIN", title="Venture Company Mining", questId=600, coords={ x=27.11, y=77.22 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.11, 77.22)" },
    { type="TURNIN", title="Skullsplitter Tusks", questId=209, coords={ x=27.01, y=77.14 }, npc = { name="Kebok" }, note="Kebok in The Salty Sailor Tavern (27.01, 77.14)" },
    { type="TURNIN", title="Water Elementals", questId=601, coords={ x=27.2, y=76.9 }, npc = { name="Baron Revilgaz" }, note="Baron Revilgaz in Booty Bay (27.20, 76.90)" },
    { type="TURNIN", title="Some Assembly Required", questId=577, coords={ x=28.29, y=77.6 }, npc = { name="Drizzlik" }, note="Drizzlik in Booty Bay (28.29, 77.60)" },
    { type="ACCEPT", title="Excelsior", questId=628, coords={ x=28.29, y=77.6 }, npc = { name="Drizzlik" }, note="Drizzlik in Booty Bay (28.29, 77.60)" },
    { type="TRAVEL", coords={ x=27.98, y=73.57 }, note="Travel to Southern Savage Coast (27.98, 73.57) (29.69, 72.34) (27.29, 69.51)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=595, coords={ x=27.29, y=69.51 }, npc = { name="Bloodsail Correspondence" }, note="Bloodsail Correspondence in Southern Savage Coast, it's a parchment on top of a barrel (27.29, 69.51)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=597, coords={ x=27.29, y=69.51 }, npc = { name="Bloodsail Correspondence" }, note="Bloodsail Correspondence in Southern Savage Coast (27.29, 69.51)" },
    { type="COMPLETE", title="Venture Company Mining", questId=600, coords={ x=40.14, y=42.57 }, note="Kill Venture Co. Surveyor or Venture Co. Strip Miner and collect 10 Singing Blue Crystal. You can skip this for now if you find it too difficult (40.14, 42.57) (41.72, 44.57)" },
    { type="TRAVEL", coords={ x=28.3, y=72.94 }, note="Travel jsut outside of the Booty Bay entrance. (28.30, 72.94)" },
    { type="TURNIN", title="Scaring Shaky", questId=606, coords={ x=26.9, y=73.6 }, npc = { name="Phillipe" }, note="\"Shaky\" Phillipe in Booty Bay (26.90, 73.60)" },
    { type="ACCEPT", title="Return to MacKinley", questId=607, coords={ x=26.9, y=73.6 }, npc = { name="Phillipe" }, note="\"Shaky\" Phillipe in Booty Bay (26.90, 73.60)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=597, coords={ x=28.08, y=76.23 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.23)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=599, coords={ x=28.08, y=76.23 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.23)" },
    { type="TURNIN", title="Return to MacKinley", questId=607, coords={ x=27.76, y=77.09 }, npc = { name="MacKinley" }, note="\"Sea Wolf\" MacKinley in Booty Bay (27.76, 77.09)" },
    { type="ACCEPT", title="Voodoo Dues", questId=609, coords={ x=27.76, y=77.09 }, npc = { name="MacKinley" }, note="\"Sea Wolf\" MacKinley in Booty Bay (27.76, 77.09)" },
    { type="ACCEPT", title="Up to Snuff", questId=587, coords={ x=26.94, y=77.34 }, npc = { name="Deeg" }, note="Deeg in The Salty Sailor Tavern (26.94, 77.34)" },
    { type="TURNIN", title="Venture Company Mining", questId=600, coords={ x=27.11, y=77.22 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.11, 77.22)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=599, coords={ x=27.17, y=76.98 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.17, 76.98)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=604, coords={ x=27.17, y=76.98 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.17, 76.98)" },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 1. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 4. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 6. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 8. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 10. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 11. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 14. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 16. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 18. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 20. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 21. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 24. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 25. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 26. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 27. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="Store Seahorn's Sealed Letter to the bank (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Withdraw Fizzle Brassbolts' Letter from the bank. Tick this step (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Withdraw Ensorcelled Parchment from the bank. Tick this step (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="TRAVEL", coords={ x=33.27, y=32.31 }, note="Travel to The Savage Coast (33.27, 32.31)" },
    { type="COMPLETE", title="Excelsior", questId=628, coords={ x=33.27, y=32.31 }, note="Kill a Elder Saltwater Crocolisk and collect Elder Crocolisk Skin in The Savage Coast (33.27, 32.31) (30.85, 29.81) (29.84, 25.61)" },
    { type="TRAVEL", coords={ x=35.65, y=10.51 }, note="Travel to Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter I", questId=339, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter II", questId=340, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter III", questId=341, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter IV", questId=342, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter I", questId=339, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter II", questId=340, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter III", questId=341, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter IV", questId=342, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="TRAVEL", coords={ x=28.29, y=77.6 }, note="Travel or Hearthstone to Booty Bay (28.29, 77.60)" },
    { type="TURNIN", title="Excelsior", questId=628, coords={ x=28.29, y=77.6 }, npc = { name="Drizzlik" }, note="Drizzlik in Booty Bay (28.29, 77.60)" },
    { type="NOTE", class="Paladin", note="Grind to Level 40 so you can get (spell:13819) ability" },
    { type="ACCEPT", class="Paladin", race="Dwarf", title="The Tome of Nobility", questId=4486, coords={ x=23.32, y=6.33 }, npc = { name="Brandur Ironhammer" }, note="Brandur Ironhammer in Hall of Mysteries (23.32, 6.33)" },
    { type="TURNIN", class="Paladin", race="Dwarf", title="The Tome of Nobility", questId=4486, coords={ x=39.83, y=29.83 }, npc = { name="Duthorian Rall" }, note="Duthorian Rall in Cathedral of Light (39.83, 29.83)" },
    { type="ACCEPT", class="Paladin", race="Human", title="The Tome of Nobility", questId=4485, coords={ x=38.67, y=32.91 }, npc = { name="Arthur" }, note="Arthur the Faithful in Cathedral of Light (38.67, 32.91)" },
    { type="TURNIN", class="Paladin", race="Human", title="The Tome of Nobility", questId=4485, coords={ x=39.86, y=29.78 }, npc = { name="Duthorian Rall" }, note="Duthorian Rall in Cathedral of Light (39.86, 29.78)" },
    { type="NOTE", class="Paladin", note="Speak to Arthur the Faithful and train (spell:13819) (38.67, 32.91)", coords={ x=38.67, y=32.91 } },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
