-- =========================
-- QS_Stranglethorn_42_43.lua
-- Converted from TourGuide format on 2025-08-16 22:16:22
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Stranglethorn_42_43"] = {
  title    = "Stranglethorn (42-43)",
  next     = "Desolace (43-43)",
  nextKey  = "QS_Desolace_43_43",
  faction  = "Alliance",
  minLevel = 42,
  maxLevel = 43,
  steps = {
    { type="TRAVEL", coords={ x=27.0, y=77.2 }, note="Travel to Booty Bay (27.0, 77.2)" },
    { type="ACCEPT", title="Tran'rek", questId=2864, coords={ x=27.0, y=77.2 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern, on second floor (27.0, 77.2)" },
    { type="ACCEPT", title="Zanzil's Secret", questId=621, coords={ x=27.1, y=77.3 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern, on ground floor (27.1, 77.3)" },
    { type="SET_HEARTH", title="Akiris by the Bundle", coords={ x=27.1, y=77.3 }, npc = { name="Innkeeper Skindle" }, note="Speak to Innkeeper Skindle and set hearth at The Salty Sailor Tavern (27.1, 77.3)" },
    { type="ACCEPT", title="Akiris by the Bundle", questId=617, coords={ x=26.7, y=76.4 }, npc = { name="Privateer Bloads" }, note="Privateer Bloads in Booty Bay, near the bank. (26.7, 76.4)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=595, coords={ x=28.08, y=76.19 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.19)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=599, coords={ x=27.1, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.1, 77.0)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=595, coords={ x=27.29, y=69.51 }, npc = { name="Bloodsail Correspondence" }, note="Bloodsail Correspondence in Southern Savage Coast, it's a parchment on top of a barrel (27.29, 69.51)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=597, coords={ x=27.29, y=69.51 }, npc = { name="Bloodsail Correspondence" }, note="Bloodsail Correspondence in Southern Savage Coast (27.29, 69.51)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=597, coords={ x=28.08, y=76.23 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.23)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=599, coords={ x=28.08, y=76.23 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.23)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=599, coords={ x=27.17, y=76.98 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.17, 76.98)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=604, coords={ x=27.1, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.1, 77.0)" },
    { type="TURNIN", title="Singing Blue Shards", questId=605, coords={ x=27.11, y=77.21 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub, in The Salty Sailor Tavern (27.11, 77.21)" },
    { type="ACCEPT", title="Venture Company Mining", questId=600, coords={ x=27.1, y=77.3 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.1, 77.3)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=599, coords={ x=27.1, y=77.0 }, note="At Fleet Master Seahorn on the 2nd Floor of the Inn (27.1, 77)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=604, coords={ x=27.1, y=77.0 }, note="At Fleet Master Seahorn (27.1, 77)" },
    { type="ACCEPT", title="Voodoo Dues", questId=609, coords={ x=27.79, y=77.08 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.79, 77.08)" },
    { type="ACCEPT", title="Stoley's Debt", questId=2872, coords={ x=27.8, y=77.1 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.8, 77.1)" },
    { type="ACCEPT", title="Keep An Eye Out", questId=576, coords={ x=28.6, y=75.8 }, npc = { name="Dizzy One-Eye" }, note="Dizzy One-Eye in Booty Bay (28.6, 75.8)" },
    { type="TRAVEL", coords={ x=30.85, y=72.37 }, note="Travel to Wild Shore (30.85, 72.37) (32.93, 74.27)" },
    { type="NOTE", note="Collect Bloodsail Charts on top the table in Wild Shore (26.9, 82.5)", coords={ x=26.9, y=82.5 } },
    { type="NOTE", note="Collect Bloodsail Orders on top of the crate in Wild Shore (27.8, 83.1)", coords={ x=27.8, y=83.1 } },
    { type="COMPLETE", title="The Bloodsail Buccaneers", questId=604, coords={ x=30.31, y=80.75 }, note="Kill 10 Bloodsail Swashbuckler in Wild Shore (30.31, 80.75)" },
    { type="COMPLETE", title="Up to Snuff", questId=587, coords={ x=30.0, y=80.0 }, note="Kill Bloodsail pirates and collect 15 Snuff in Wild Shore (30, 80)" },
    { type="COMPLETE", title="Keep An Eye Out", questId=576, coords={ x=30.0, y=80.0 }, note="The Pirates should have dropped Dizzy's Eye by now, or else keep killing pirates until you find one (30, 80)" },
    { type="TRAVEL", coords={ x=27.1, y=77.3 }, note="Travel or Hearthstone to Booty Bay (27.1, 77.3)" },
    { type="TURNIN", title="Up to Snuff", questId=587, coords={ x=27.0, y=77.3 }, npc = { name="Deeg" }, note="Deeg in Booty Bay (27.0, 77.3)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=604, coords={ x=27.1, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.1, 77.0)" },
    { type="TURNIN", title="Keep An Eye Out", questId=576, coords={ x=28.6, y=75.8 }, npc = { name="Dizzy One-Eye" }, note="Dizzy One-Eye in Booty Bay (28.6, 75.8)" },
    { type="TRAVEL", coords={ x=30.85, y=72.37 }, note="Travel to Southern Savage Coast (30.85, 72.37) (28.88, 58.10)" },
    { type="COMPLETE", title="Akiris by the Bundle", questId=617, coords={ x=24.0, y=65.0 }, note="Collect 10 Bundles of Akiris Reed from the Naga Explorer (24, 65)" },
    { type="TRAVEL", coords={ x=27.16, y=58.98 }, note="Travel to Ruins of Jubuwal (27.16, 58.98) (29.81, 56.60)(30.88, 53.61) (34.75, 51.82)" },
    { type="NOTE", note="Collect 12 Zanzil's Mixture drop from any Zanzil mobs" },
    { type="COMPLETE", title="Voodoo Dues", questId=609, coords={ x=34.75, y=51.82 }, note="Kill Jon-Jon the Crow and collect Jon-Jon's Golden Spyglass in Ruins of Jubuwal (34.75, 51.82) | Kill Maury \\Club Foot\\ Wilkins and collect Maury's Clubbed Foot in Ruins of Jubuwal (35.18, 51.11)" },
    { type="TRAVEL", note="Travel to Stranglethorn Vale" },
    { type="COMPLETE", title="Venture Company Mining", questId=600, coords={ x=40.14, y=42.57 }, note="Kill the Venture Co. goblins for 10 Singing Blue Crystal (40.14, 42.57) (41.72, 44.57)" },
    { type="TRAVEL", coords={ x=33.9, y=54.0 }, note="Travel to Ruins of Aboraz (33.90, 54.00) (38.34, 56.71)" },
    { type="COMPLETE", title="Voodoo Dues", questId=609, coords={ x=40.05, y=58.21 }, note="Kill Maury \\Club Foot\\ Wilkins and collect Chucky's Huge Ring in Ruins of Aboraz (40.05, 58.21)" },
    { type="COMPLETE", title="Zanzil's Secret", questId=621, coords={ x=40.0, y=57.0 }, note="Kill Zanzil Hunter and Zanzil Zombie at the Ruins of Aboraz for 12 Zanzil's Mixture (40, 57)" },
    { type="TRAVEL", coords={ x=35.7, y=10.8 }, note="Travel to Nesingwary's Expedition (35.7, 10.8)" },
    { type="COMPLETE", title="Raptor Mastery", questId=197, coords={ x=28.0, y=44.0 }, note="Kill Tethis and loot Talon of Tethis (28, 44)" },
    { type="TURNIN", title="Raptor Mastery", questId=197, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="ACCEPT", title="Big Game Hunter", questId=208, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="COMPLETE", title="Big Game Hunter", questId=208, coords={ x=38.0, y=35.0 }, note="Kill King Bangalash and loot the Head of Bangalash (38, 35)" },
    { type="TRAVEL", coords={ x=35.7, y=10.8 }, note="Travel to Nesingwary's Expedition (35.7, 10.8)" },
    { type="TURNIN", title="Big Game Hunter", questId=208, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="TRAVEL", coords={ x=27.1, y=77.3 }, note="Travel or Hearthstone to Booty Bay (27.1, 77.3)" },
    { type="TURNIN", title="Zanzil's Secret", questId=621, coords={ x=27.1, y=77.3 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.1, 77.3)" },
    { type="TURNIN", title="Up to Snuff", questId=587, coords={ x=27.0, y=77.3 }, npc = { name="Deeg" }, note="Deeg in Booty Bay (27.0, 77.3)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=604, coords={ x=27.1, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.1, 77.0)" },
    { type="TURNIN", title="Akiris by the Bundle", questId=617, coords={ x=26.7, y=76.4 }, npc = { name="Privateer Bloads" }, note="Privateer Bloads in Booty Bay (26.7, 76.4)" },
    { type="ACCEPT", title="Akiris by the Bundle", questId=623, coords={ x=26.7, y=76.4 }, npc = { name="Privateer Bloads" }, note="Privateer Bloads in Booty Bay (26.7, 76.4)" },
    { type="TURNIN", title="Voodoo Dues", questId=609, coords={ x=27.8, y=77.1 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay - Skip follow up (27.8, 77.1)" },
    { type="ACCEPT", title="Stoley's Debt", questId=2872, coords={ x=27.79, y=77.08 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.79, 77.08)" },
    { type="TURNIN", title="Keep An Eye Out", questId=576, coords={ x=28.6, y=75.8 }, npc = { name="Dizzy One-Eye" }, note="Dizzy One-Eye in Booty Bay (28.6, 75.8)" },
    { type="ACCEPT", title="Magical Analysis", questId=602, coords={ x=27.2, y=76.9 }, npc = { name="Baron Revilgaz" }, note="Baron Revilgaz in Booty Bay (27.20, 76.90)" },
    { type="NOTE", note="Withdraw Goblin Rumors from the bank. Tick this step (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Withdraw Pristine Crawler Leg from the bank. Tick this step (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Withdraw Draenethyst Shard from the bank. Tick this step (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Store Goblin Rumors to the bank (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Store Bag of Water Elemental Bracers to the bank (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Store Encrusted Tail Fin to the bank (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Store Carefully Folded Note" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
