-- =========================
-- QS_Stranglethorn_46_47.lua
-- Converted from TourGuide format on 2025-08-16 22:16:24
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Stranglethorn_46_47"] = {
  title    = "Stranglethorn (46-47)",
  next     = "Searing Gorge (47-48)",
  nextKey  = "QS_Searing_Gorge_47_48",
  faction  = "Alliance",
  minLevel = 46,
  maxLevel = 47,
  steps = {
    { type="TRAVEL", coords={ x=27.78, y=77.07 }, note="Travel to Booty Bay (27.78, 77.07)" },
    { type="TURNIN", title="Deliver to MacKinley", questId=2874, coords={ x=27.78, y=77.07 }, npc = { name="Sea Wolf MacKinley" }, note="Sea Wolf MacKinley in Booty Bay (27.78, 77.07)" },
    { type="NOTE", note="Store Drawing Kit to the bank (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Store Standard Issue Flare Gun to the bank (26.57, 76.56)", coords={ x=26.57, y=76.56 } },
    { type="NOTE", note="Withdraw Carefully Folded Note" },
    { type="SET_HEARTH", title="\"Pretty Boy\" Duncan", coords={ x=27.05, y=77.32 }, npc = { name="Innkeeper Skindle" }, note="Speak to Innkeeper Skindle to set your hearth at The Salty Sailor Tavern (27.05, 77.32)" },
    { type="ACCEPT", title="South Seas Delicacy", questId=60155, coords={ x=27.0, y=77.3 }, npc = { name="Innkeeper Skindle" }, note="Innkeeper Skindle in The Salty Sailor Tavern (27.0, 77.3)" },
    { type="TURNIN", title="Back to Booty Bay", questId=1118, coords={ x=27.12, y=77.23 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.12, 77.23)" },
    { type="TURNIN", title="Ansirem's Key", questId=603, coords={ x=27.27, y=77.52 }, npc = { name="Catelyn" }, note="Catelyn the Blade in The Salty Sailor Tavern (27.27, 77.52)" },
    { type="ACCEPT", title="\"Pretty Boy\" Duncan", questId=610, coords={ x=27.27, y=77.52 }, npc = { name="Catelyn" }, note="Catelyn the Blade in The Salty Sailor Tavern (27.27, 77.52)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=608, coords={ x=27.2, y=76.91 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.20, 76.91)" },
    { type="ACCEPT", title="They Call Him Morgan the Storm", questId=60152, coords={ x=27.2, y=76.9 }, npc = { name="Baron Revilgaz" }, note="Baron Revilgaz in Booty Bay (27.2, 76.9)" },
    { type="ACCEPT", title="The Captain's Chest", questId=614, coords={ x=26.7, y=73.61 }, npc = { name="Captain Hecklebury Smotts" }, note="Captain Hecklebury Smotts in Booty Bay (26.70, 73.61)" },
    { type="TRAVEL", coords={ x=29.63, y=72.36 }, note="Travel to Southern Savage Coast (29.63, 72.36) (27.42, 69.43)" },
    { type="COMPLETE", title="\"Pretty Boy\" Duncan", questId=610, coords={ x=27.42, y=69.43 }, note="Kill \\Pretty Boy\\ Duncan and collect Catelyn's Blade in Southern Savage Coast (27.42, 69.43)" },
    { type="TRAVEL", coords={ x=33.77, y=74.85 }, note="Travel to Wild Shore (33.77, 74.85)" },
    { type="NOTE", note="Look for a Half Burried Bottle (green) along the beach and check it for Carefully Folded Note to start quest" },
    { type="COMPLETE", title="The Captain's Chest", questId=614, coords={ x=33.77, y=74.85 }, note="Kill Gorlash and collect Smotts' Chest in The Crystal Shore. Gorlash is a level 47 Elite and you might need help to kill him otherwise it is safe to skip (33.77, 74.85) (39.19, 60.70) (36.95, 69.73)" },
    { type="TURNIN", title="They Call him Morgan the Storm", questId=60152, coords={ x=32.4, y=82.1 }, npc = { name="Morgan" }, note="Morgan the Storm in Wild Shore (32.4,82.1)" },
    { type="ACCEPT", title="The Iron Patch", questId=60153, coords={ x=32.4, y=82.1 }, npc = { name="Morgan" }, note="Morgan the Storm in Wild Shore (32.4,82.1)" },
    { type="NOTE", note="Look for a Half Burried Bottle (green) along the beach and check it for Carefully Folded Note to start quest (34.6, 73.0) (33.9, 76.7) (39.73, 77.39)", coords={ x=34.6, y=73.0 } },
    { type="ACCEPT", title="Message in a Bottle", questId=594, note="Use Carefully Folded Note to accept quest" },
    { type="TRAVEL", coords={ x=38.51, y=80.58 }, note="Travel to Jaguero Isle (38.51, 80.58)" },
    { type="TURNIN", title="Message in a Bottle", questId=594, coords={ x=38.51, y=80.58 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in Jaguero Isle (38.51, 80.58)" },
    { type="NOTE", note="Check the bottom floor of each ship for Cortello's Riddle or in the captain's room, it can spawn in one of the three ship. Collect 15 Snuff from any pirates" },
    { type="NOTE", note="Kill any Southern Sand Crawlers you see along the way for Southern Sand Crawler Legs" },
    { type="COMPLETE", title="The Bloodsail Buccaneers", questId=608, coords={ x=32.82, y=88.33 }, note="Kill Captain Stillwater in the middle floor of the ship in Wild Shore (32.82, 88.33) | Kill Garr Salthoof in the middle floor of the ship in Wild Shore (30.17, 89.40) (30.63, 90.57) | Kill Captain Keelhaul in the middle floor of the ship in Wild Shore (29.87, 89.35) (29.20, 88.38)" },
    { type="COMPLETE", title="Iron Patch", questId=60153, coords={ x=30.6, y=90.4 } },
    { type="NOTE", note="Check the bottom floor of each ship for Cortello's Riddle or in the captain's room, it can spawn in one of the three ship (29.18, 88.63)", coords={ x=29.18, y=88.63 } },
    { type="ACCEPT", title="Cortello's Riddle", questId=624, note="Use Cortello's Riddle to accept quest" },
    { type="NOTE", note="You can now destroy Cortello's Riddle, if you already accepted the quest. Tick this step" },
    { type="COMPLETE", title="Up to Snuff", questId=587, coords={ x=33.14, y=88.25 }, note="Collect 15 Snuff from any pirates in Wild Shore (33.14, 88.25)" },
    { type="COMPLETE", title="South Seas Delicacy", questId=60155, coords={ x=34.0, y=85.9 }, note="Collect 10 Southern Sand Crawler Leg from Crawlers in Wild Shore (34.0, 85.9) (29.9, 87.3) (26.7, 87.0) (26.9, 84.3) (31.3, 81.9)" },
    { type="TRAVEL", coords={ x=27.27, y=77.52 }, note="Travel to Booty Bay (27.27, 77.52)" },
    { type="ACCEPT", title="Whiskey Slim's Lost Grog", questId=580, coords={ x=27.12, y=77.43 }, npc = { name="Whiskey Slim" }, note="Whiskey Slim in The Salty Sailor Tavern (27.12, 77.43)" },
    { type="TURNIN", title="South Seas Delicacy", questId=60155, coords={ x=27.0, y=77.3 }, npc = { name="Innkeeper Skindle" }, note="Innkeeper Skindle in The Salty Sailor Tavern (27.0, 77.3)" },
    { type="TURNIN", title="\"Pretty Boy\" Duncan", questId=610, coords={ x=27.27, y=77.52 }, npc = { name="Catelyn" }, note="Catelyn the Blade in The Salty Sailor Tavern (27.27, 77.52)" },
    { type="ACCEPT", title="The Curse of the Tides", questId=611, coords={ x=27.27, y=77.52 }, npc = { name="Catelyn" }, note="Catelyn the Blade in The Salty Sailor Tavern (27.27, 77.52)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=608, coords={ x=27.19, y=76.99 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.19, 76.99)" },
    { type="TURNIN", title="The Iron Patch", questId=60153, note="Baron Revilgaz" },
    { type="ACCEPT", title="Stranglethorn Fever", questId=348, coords={ x=27.63, y=76.75 }, npc = { name="Fin Fizracket" }, note="Fin Fizracket in Booty Bay (27.63, 76.75)" },
    { type="TURNIN", title="The Captain's Chest", questId=614, coords={ x=26.69, y=73.62 }, npc = { name="Captain Hecklebury Smotts" }, note="Captain Hecklebury Smotts in Booty Bay (26.69, 73.62)" },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 1. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 4. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 6. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 8. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 10. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 11. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 14. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 16. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 18. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 20. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 21. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 24. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 25. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 26. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 27. Try to purchase from the auction house Auctioneer O\\'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="TRAVEL", coords={ x=33.69, y=65.08 }, note="Travel to Mistvale Valley (33.69, 65.08)" },
    { type="NOTE", note="Kill Elder Mistvale Gorilla until you collect 10 Gorilla Fang for the quest 'Strangelthorn Fever' in Mistvale Valley (33.69, 65.08)", coords={ x=33.69, y=65.08 } },
    { type="TURNIN", title="Stranglethorn Fever", questId=349, coords={ x=35.28, y=60.39 }, npc = { name="Witch Doctor Unbagwa" }, note="Witch Doctor Unbagwa in Spirit Den, this will start the event (35.28, 60.39)" },
    { type="COMPLETE", title="Stranglethorn Fever", questId=348, coords={ x=35.17, y=60.54 }, note="Survive the wave of attack until Mokk the Savage spawn, kill him for Heart of Mokk in Spirit Den (35.17, 60.54)" },
    { type="TRAVEL", coords={ x=35.7, y=10.8 }, note="Travel to Nesingwary's Expedition (35.7, 10.8)" },
    { type="COMPLETE", title="Raptor Mastery", questId=197, coords={ x=28.0, y=44.0 }, note="Kill Tethis and loot Talon of Tethis (28, 44)" },
    { type="COMPLETE", title="The Curse of the Tides", questId=611, coords={ x=24.9, y=23.56 }, note="Click on the Altar of Tides and Gazban will spawn, kill him and collect Stone of the Tides in The Vile Reef (24.90, 23.56)" },
    { type="TURNIN", title="Raptor Mastery", questId=197, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="ACCEPT", title="Big Game Hunter", questId=208, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="COMPLETE", title="Big Game Hunter", questId=208, coords={ x=38.0, y=35.0 }, note="Kill King Bangalash and loot the Head of Bangalash (38, 35)" },
    { type="TRAVEL", coords={ x=35.7, y=10.8 }, note="Travel to Nesingwary's Expedition (35.7, 10.8)" },
    { type="TURNIN", title="Big Game Hunter", questId=208, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="ACCEPT", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter I", questId=339, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter II", questId=340, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter III", questId=341, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter IV", questId=342, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter I", questId=339, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter II", questId=340, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter III", questId=341, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter IV", questId=342, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="TRAVEL", coords={ x=27.64, y=76.75 }, note="Travel to Booty Bay (27.64, 76.75)" },
    { type="TURNIN", title="The Curse of the Tides", questId=611, coords={ x=27.2, y=76.9 }, npc = { name="Baron Revilgaz" }, note="Baron Revilgaz in Booty Bay (27.20, 76.90)" },
    { type="TURNIN", title="Stranglethorn Fever", questId=348, coords={ x=27.64, y=76.75 }, npc = { name="Fin Fizracket" }, note="Fin Fizracket in Booty Bay (27.64, 76.75)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
