-- =========================
-- QS_Badlands_40_41.lua
-- Converted from TourGuide format on 2025-08-16 19:50:37
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Badlands_40_41"] = {
  title    = "Badlands (40-41)",
  next     = "Swamp of Sorrows (41-42)",
  nextKey  = "QS_Swamp_of_Sorrows_41_42",
  faction  = "Alliance",
  minLevel = 40,
  maxLevel = 41,
  steps = {
    { type="ACCEPT", class="Paladin", race="Dwarf", title="The Tome of Nobility", questId=4486, coords={ x=23.32, y=6.33 }, npc = { name="Brandur Ironhammer" }, note="Brandur Ironhammer in Hall of Mysteries (23.32, 6.33)" },
    { type="TURNIN", class="Paladin", race="Dwarf", title="The Tome of Nobility", questId=4486, coords={ x=39.83, y=29.83 }, npc = { name="Duthorian Rall" }, note="Duthorian Rall in Cathedral of Light (39.83, 29.83)" },
    { type="ACCEPT", class="Paladin", race="Human", title="The Tome of Nobility", questId=4485, coords={ x=38.67, y=32.91 }, npc = { name="Arthur" }, note="Arthur the Faithful in Cathedral of Light (38.67, 32.91)" },
    { type="TURNIN", class="Paladin", race="Human", title="The Tome of Nobility", questId=4485, coords={ x=39.86, y=29.78 }, npc = { name="Duthorian Rall" }, note="Duthorian Rall in Cathedral of Light (39.86, 29.78)" },
    { type="NOTE", class="Paladin", note="Speak to Arthur the Faithful and train Summon Warhorse (38.67, 32.91)", coords={ x=38.67, y=32.91 } },
    { type="TRAVEL", coords={ x=24.0, y=70.0 }, note="Travel to City of Ironforge (24, 70)" },
    { type="NOTE", note="Buy Frost Oil from Auction House. Skip this if not available. Don't buy if this is your first character and you still need to purchase a mount (24, 70)", coords={ x=24.0, y=70.0 } },
    { type="NOTE", note="Buy Gyrochronatom from Auction House. Don't buy if you didn't find a Frost Oil. Don't buy if this is your first character and you still need to purchase a mount (24, 70)", coords={ x=24.0, y=70.0 } },
    { type="NOTE", note="Buy Healing Potion from Auction House. Don't buy if you didn't find a Frost Oil and Gyrochronatom. Don't buy if this is your first character and you still need to purchase a mount (24, 70)", coords={ x=24.0, y=70.0 } },
    { type="NOTE", note="Buy Lesser Invisibility Potion from Auction House. Don't buy if you didn't find a Frost Oil and Gyrochronatom. Don't buy if this is your first character and you still need to purchase a mount (24, 70)", coords={ x=24.0, y=70.0 } },
    { type="NOTE", note="Buy 4 Buzzard Wing from Auction House - Skip this if not available (24, 70)", coords={ x=24.0, y=70.0 } },
    { type="ACCEPT", title="Ironband Wants You!", questId=707, coords={ x=74.57, y=11.68 }, npc = { name="Prospector Stormpike" }, note="Prospector Stormpike in The Library (74.57, 11.68)" },
    { type="TURNIN", title="Stormpike's Deciphering", questId=554, coords={ x=74.57, y=11.68 }, npc = { name="Prospector Stormpike" }, note="Prospector Stormpike in The Library (74.57, 11.68)" },
    { type="NOTE", note="Withdraw Fizzle Brassbolts' Letter from the bank. Tick this step (35.48, 60.70)", coords={ x=35.48, y=60.7 } },
    { type="TRAVEL", coords={ x=37.0, y=49.2 }, note="Travel to Loch Modan (37, 49.2)" },
    { type="ACCEPT", title="Badlands Reagent Run", questId=2500, coords={ x=37.06, y=49.36 }, npc = { name="Ghak Healtouch" }, note="Ghak Healtouch in Thelsamar (37.06, 49.36)" },
    { type="TRAVEL", coords={ x=65.94, y=65.62 }, note="Travel to Ironband's Excavation Site (65.94, 65.62)" },
    { type="TURNIN", title="Ironband Wants You!", questId=707, coords={ x=65.94, y=65.62 }, npc = { name="Prospector Ironband" }, note="Prospector Ironband in Ironband's Excavation Site (65.94, 65.62)" },
    { type="ACCEPT", title="Find Agmond", questId=738, coords={ x=65.94, y=65.62 }, npc = { name="Prospector Ironband" }, note="Prospector Ironband in Ironband's Excavation Site (65.94, 65.62)" },
    { type="TRAVEL", coords={ x=53.7, y=43.3 }, note="Travel south to Badlands (53.7, 43.3)" },
    { type="NOTE", note="Kill every Starving Buzzard you come across as they are quite rare and collect 4 Buzzard Wing and 5 Buzzard Gizzard. Kill any Coyotes for 10 Crag Coyote Fang" },
    { type="ACCEPT", title="Fiery Blaze Enchantments", questId=706, coords={ x=53.7, y=43.3 }, npc = { name="Sigrun Ironhew" }, note="Sigrun Ironhew in Badlands (53.7, 43.3)" },
    { type="ACCEPT", title="Mirages", questId=718, coords={ x=53.7, y=43.3 }, npc = { name="Sigrun Ironhew" }, note="Sigrun Ironhew in Badlands (53.7, 43.3)" },
    { type="ACCEPT", title="A Dwarf and His Tools", questId=719, coords={ x=53.4, y=43.4 }, npc = { name="Prospector Ryedol" }, note="Prospector Ryedol in Badlands (53.4, 43.4)" },
    { type="TRAVEL", coords={ x=42.37, y=52.94 }, note="Travel to Valley of Fangs (42.37, 52.94)" },
    { type="TURNIN", title="Martek the Exiled", questId=1106, coords={ x=42.27, y=52.62 }, npc = { name="Martek" }, note="Martek the Exiled in Valley of Fangs (42.27, 52.62)" },
    { type="ACCEPT", title="Indurium", questId=1108, coords={ x=42.27, y=52.62 }, npc = { name="Martek" }, note="Martek the Exiled in Valley of Fangs (42.27, 52.62)" },
    { type="ACCEPT", title="Barbecued Buzzard Wings", questId=703, coords={ x=42.37, y=52.94 }, npc = { name="Rigglefuzz" }, note="Rigglefuzz in Valley of Fangs (42.37, 52.94)" },
    { type="TRAVEL", coords={ x=66.9, y=23.46 }, note="Travel to Camp Kosh (66.90, 23.46)" },
    { type="COMPLETE", title="Mirages", questId=718, coords={ x=66.9, y=23.46 }, note="Collect Supply Crate from the Excavation Supply Crate in Camp Kosh (66.90, 23.46)" },
    { type="TRAVEL", coords={ x=53.0, y=34.1 }, note="Travel to Hammertoe's Digsite (53, 34.1)" },
    { type="ACCEPT", title="A Sign of Hope", questId=720, coords={ x=53.0, y=34.1 }, npc = { name="Crumpled Map" }, note="Crumpled Map in Hammertoe's Digsite (53, 34.1)" },
    { type="COMPLETE", title="A Dwarf and His Tools", questId=719, coords={ x=51.0, y=31.0 }, note="Kill Shadowforge mobs until you find Ryedol's Lucky Pick in Hammertoe's Digsite (51, 31)" },
    { type="TURNIN", title="Mirages", questId=718, coords={ x=53.7, y=43.3 }, npc = { name="Sigrun Ironhew" }, note="Sigrun Ironhew in Badlands (53.7, 43.3)" },
    { type="ACCEPT", title="Scrounging", questId=733, coords={ x=53.7, y=43.3 }, npc = { name="Sigrun Ironhew" }, note="Sigrun Ironhew in Badlands (53.7, 43.3)" },
    { type="TURNIN", title="A Dwarf and His Tools", questId=719, coords={ x=53.4, y=43.4 }, npc = { name="Prospector Ryedol" }, note="Prospector Ryedol in Badlands (53.4, 43.4)" },
    { type="TURNIN", title="A Sign of Hope", questId=720, coords={ x=53.4, y=43.4 }, npc = { name="Prospector Ryedol" }, note="Prospector Ryedol in Badlands (53.4, 43.4)" },
    { type="ACCEPT", title="Tremors of the Earth", questId=732, coords={ x=61.91, y=54.23 }, npc = { name="Garek" }, note="Garek in Badlands (61.91, 54.23)" },
    { type="TURNIN", title="Find Agmond", questId=738, coords={ x=50.92, y=62.36 }, npc = { name="Battered Dwarven Skeleton" }, note="Battered Dwarven Skeleton in Agmond's End (50.92, 62.36)" },
    { type="ACCEPT", title="Murdaloc", questId=739, coords={ x=50.92, y=62.36 }, npc = { name="Battered Dwarven Skeleton" }, note="Battered Dwarven Skeleton in Agmond's End (50.92, 62.36)" },
    { type="NOTE", note="Collect 10 Indurium Flake from Stonevault mobs in Agmond's End" },
    { type="COMPLETE", title="Murdaloc", questId=739, coords={ x=49.75, y=66.9 }, note="Find and kill Murdaloc in Agmond's End (49.75, 66.90) | Kill 12 Stonevault Bonesnapper or Stonevault Shaman found nearby at Agmond's End (50, 70)" },
    { type="COMPLETE", title="Indurium", questId=1108, coords={ x=49.97, y=68.31 }, note="Collect 10 Indurium Flake from Stonevault mobs in Agmond's End (49.97, 68.31)" },
    { type="TURNIN", title="Indurium", questId=1108, coords={ x=42.2, y=52.72 }, npc = { name="Martek" }, note="Martek the Exiled in Valley of Fangs (42.20, 52.72)" },
    { type="TRAVEL", coords={ x=50.92, y=62.36 }, note="Travel to Agmond's End (50.92, 62.36)" },
    { type="NOTE", note="Kill every Starving Buzzard you come across and collect 4 Buzzard Wing and 5 Buzzard Gizzard. Kill any Coyotes for 10 Crag Coyote Fang" },
    { type="COMPLETE", title="Tremors of the Earth", questId=732, coords={ x=11.0, y=72.0 }, note="Kill Boss Tho'grun who patrol down to the southwest side of the zone and back in a circle. You should be able to pick Boss Tho'grun off the back of the pack easily (11, 72) (18, 79.7) (59, 69) (48, 51) (29.5, 59) (23, 52)" },
    { type="TRAVEL", coords={ x=50.92, y=62.36 }, note="Travel to Agmond's End (50.92, 62.36)" },
    { type="COMPLETE", title="Barbecued Buzzard Wings", questId=703, coords={ x=52.75, y=26.28 }, note="Kill Starving Buzzard and collect 4 Buzzard Wing (52.75, 26.28)" },
    { type="TURNIN", title="Barbecued Buzzard Wings", questId=703, coords={ x=42.37, y=52.94 }, npc = { name="Rigglefuzz" }, note="Rigglefuzz in Valley of Fangs (42.37, 52.94)" },
    { type="ACCEPT", title="News for Fizzle", questId=1137, coords={ x=42.17, y=53.1 }, npc = { name="Martek" }, note="Martek the Exiled in Valley of Fangs (42.17, 53.10)" },
    { type="TRAVEL", coords={ x=25.91, y=44.91 }, note="Travel to The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Study of the Elements: Rock", questId=710, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Coolant Heads Prevail", questId=713, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="TURNIN", title="Coolant Heads Prevail", questId=713, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Gyro... What?", questId=714, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="TURNIN", title="Gyro... What?", questId=714, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Liquid Stone", questId=715, coords={ x=25.83, y=44.29 }, npc = { name="Lucien Tosselwrench" }, note="Lucien Tosselwrench in The Dustbowl (25.83, 44.29)" },
    { type="TURNIN", title="Liquid Stone", questId=715, coords={ x=25.83, y=44.29 }, npc = { name="Lucien Tosselwrench" }, note="Lucien Tosselwrench in The Dustbowl (25.83, 44.29)" },
    { type="COMPLETE", title="Study of the Elements: Rock", questId=710, coords={ x=13.12, y=38.86 }, note="Kill the Lesser Rock Elemental and collect 10 Small Stone Shard (13.12, 38.86)" },
    { type="TURNIN", title="Study of the Elements: Rock", questId=710, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Study of the Elements: Rock", questId=711, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="COMPLETE", title="Study of the Elements: Rock", questId=711, coords={ x=15.52, y=32.18 }, note="Kill Rock Elemental until you've collected 3 Large Stone Slab. They are found either further West or to the South of Badlands (15.52, 32.18)" },
    { type="NOTE", note="Kill Rock Elementals to collect 5 Rock Elemental Shard (15.52, 32.18)", coords={ x=15.52, y=32.18 } },
    { type="TURNIN", title="Study of the Elements: Rock", questId=711, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Study of the Elements: Rock", questId=712, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="TRAVEL", coords={ x=10.58, y=77.72 }, note="Travel to Camp Cagg (10.58, 77.72)" },
    { type="COMPLETE", title="Scrounging", questId=733, coords={ x=10.58, y=77.72 }, note="Kill Dustbelcher to collect 7 pieces of Scrap Metal in Camp Cagg (10.58, 77.72)" },
    { type="COMPLETE", title="Study of the Elements: Rock", questId=712, coords={ x=17.03, y=84.4 }, note="Kill the Greater Rock Elemental and collect 5 Bracers of Rock Binding in Camp Cagg (17.03, 84.40)" },
    { type="TRAVEL", coords={ x=25.91, y=44.91 }, note="Travel to The Dustbowl (25.91, 44.91)" },
    { type="TURNIN", title="Study of the Elements: Rock", questId=712, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="This Is Going to Be Hard", questId=734, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="TURNIN", title="This Is Going to Be Hard", questId=734, coords={ x=25.83, y=44.29 }, npc = { name="Lucien Tosselwrench" }, note="Lucien Tosselwrench in The Dustbowl (25.83, 44.29)" },
    { type="ACCEPT", title="This Is Going to Be Hard", questId=777, coords={ x=25.83, y=44.29 }, npc = { name="Lucien Tosselwrench" }, note="Lucien Tosselwrench in The Dustbowl (25.83, 44.29)" },
    { type="TURNIN", title="This Is Going to Be Hard", questId=777, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="This Is Going to Be Hard", questId=778, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="COMPLETE", title="This Is Going to Be Hard", questId=778, coords={ x=25.4, y=43.6 }, note="Kill the Fam'retor Guardian patrolling around and collect Lotwil's Shackles of Elemental Binding. It is possible to solo this quest, you will need to abandon the quest and accept it again to retry, it is safe to skip (25.4, 43.6)" },
    { type="TURNIN", title="This Is Going to Be Hard", questId=778, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="TURNIN", title="Scrounging", questId=733, coords={ x=53.7, y=43.3 }, npc = { name="Sigrun Ironhew" }, note="Sigrun Ironhew in Badlands (53.7, 43.3)" },
    { type="TURNIN", title="Tremors of the Earth", questId=732, coords={ x=61.91, y=54.23 }, npc = { name="Garek" }, note="Garek in Badlands (61.91, 54.23)" },
    { type="COMPLETE", title="Fiery Blaze Enchantments", questId=706, coords={ x=69.69, y=53.67 }, note="Kill Scalding Whelp until you collect a Black Drake's Heart Lethlor Ravine (69.69, 53.67)" },
    { type="TURNIN", title="Fiery Blaze Enchantments", questId=706, coords={ x=53.7, y=43.3 }, npc = { name="Sigrun Ironhew" }, note="Sigrun Ironhew in Badlands (53.7, 43.3)" },
    { type="COMPLETE", title="Badlands Reagent Run", questId=2500, coords={ x=15.1, y=59.84 }, note="Kill Buzzards, Coyotes and Rock Elementals to collect 5 Buzzard Gizzard, 10 Crag Coyote Fang and 5 Rock Elemental Shard in Apocryphan's Rest (15.10, 59.84)" },
    { type="TRAVEL", coords={ x=65.88, y=65.59 }, note="Travel to Ironband's Excavation Site in Loch Modan (65.88, 65.59)" },
    { type="TURNIN", title="Murdaloc", questId=739, coords={ x=65.88, y=65.59 }, npc = { name="Prospector Ironband" }, note="Prospector Ironband in Ironband's Excavation Site (65.88, 65.59)" },
    { type="ACCEPT", title="Agmond's Fate", questId=704, coords={ x=65.88, y=65.59 }, npc = { name="Prospector Ironband" }, note="Prospector Ironband in Ironband's Excavation Site (65.88, 65.59)" },
    { type="TRAVEL", coords={ x=37.06, y=49.36 }, note="Travel to Thelsamar (37.06, 49.36)" },
    { type="TURNIN", title="Badlands Reagent Run", questId=2500, coords={ x=37.06, y=49.36 }, npc = { name="Ghak Healtouch" }, note="Ghak Healtouch in Thelsamar (37.06, 49.36)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
