-- =========================
-- QS_Stranglethorn_38_40.lua
-- Converted from TourGuide format on 2025-08-17 18:59:06
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Stranglethorn_38_40"] = {
  title    = "Stranglethorn (38-40)",
  next     = "Badlands (40-41)",
  nextKey  = "QS_Badlands_40_41",
  faction  = "Horde",
  minLevel = 38,
  maxLevel = 40,
  steps = {
    { type="TRAVEL", coords={ x=32.5, y=29.3 }, note="Travel to Grom'gol Base Camp (32.5, 29.3)" },
    { type="FLIGHTPATH", npc = { name="Thysta" }, coords={ x=32.5, y=29.3 }, note="Speak to Thysta and grab flight path for Grom'gol Base Camp (32.5, 29.3)" },
    { type="TRAVEL", coords={ x=35.0, y=10.0 }, note="Follow the road north, look for a little camp by the river (35, 10)" },
    { type="ACCEPT", title="Welcome to the Jungle", questId=583, coords={ x=35.68, y=10.52 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.68, 10.52)" },
    { type="TURNIN", title="Welcome to the Jungle", questId=583, coords={ x=35.65, y=10.75 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.75)" },
    { type="ACCEPT", title="Tiger Mastery", questId=185, coords={ x=35.59, y=10.64 }, npc = { name="Ajeck Rouack" }, note="Ajeck Rouack in Nesingwary's Expedition (35.59, 10.64)" },
    { type="ACCEPT", title="Panther Mastery", questId=190, coords={ x=35.56, y=10.57 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.56, 10.57)" },
    { type="ACCEPT", title="Raptor Mastery", questId=194, coords={ x=35.65, y=10.75 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.75)" },
    { type="COMPLETE", title="Tiger Mastery", questId=185, coords={ x=35.0, y=14.0 }, note="Kill 10 Young Stranglethorn Tiger slightly to the east in Stranglethorn Vale (35, 14)" },
    { type="TURNIN", title="Tiger Mastery", questId=185, coords={ x=35.59, y=10.64 }, npc = { name="Ajeck Rouack" }, note="Ajeck Rouack in Nesingwary's Expedition (35.59, 10.64)" },
    { type="ACCEPT", title="Tiger Mastery", questId=186, coords={ x=35.59, y=10.64 }, npc = { name="Ajeck Rouack" }, note="Ajeck Rouack in Nesingwary's Expedition (35.59, 10.64)" },
    { type="COMPLETE", title="Panther Mastery", questId=190, coords={ x=41.0, y=9.0 }, note="Kill 10 Young Panther to the north in Stranglethorn Vale (41, 9)" },
    { type="COMPLETE", title="Tiger Mastery", questId=186, coords={ x=30.0, y=15.0 }, note="Kill 10 Stranglethorn Tiger east of the camp in Stranglethorn Vale (30, 15)" },
    { type="TURNIN", title="Panther Mastery", questId=190, coords={ x=35.56, y=10.57 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.56, 10.57)" },
    { type="ACCEPT", title="Panther Mastery", questId=191, coords={ x=35.56, y=10.57 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.56, 10.57)" },
    { type="TURNIN", title="Tiger Mastery", questId=186, coords={ x=35.59, y=10.64 }, npc = { name="Ajeck Rouack" }, note="Ajeck Rouack in Nesingwary's Expedition (35.59, 10.64)" },
    { type="ACCEPT", title="Tiger Mastery", questId=187, coords={ x=35.59, y=10.64 }, npc = { name="Ajeck Rouack" }, note="Ajeck Rouack in Nesingwary's Expedition (35.59, 10.64)" },
    { type="COMPLETE", title="Panther Mastery", questId=191, coords={ x=29.0, y=11.0 }, note="Kill 10 Panther east of the camp in Stranglethorn Vale (29, 11)" },
    { type="COMPLETE", title="Raptor Mastery", questId=194, coords={ x=28.0, y=14.0 }, note="Kill 10 Stranglethorn Raptor east near the ruins in Stranglethorn Vale (28, 14)" },
    { type="TURNIN", title="Raptor Mastery", questId=194, coords={ x=35.65, y=10.75 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.75)" },
    { type="ACCEPT", title="Raptor Mastery", questId=195, coords={ x=35.65, y=10.75 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.75)" },
    { type="TURNIN", title="Panther Mastery", questId=191, coords={ x=35.56, y=10.57 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.56, 10.57)" },
    { type="TRAVEL", coords={ x=26.33, y=73.49 }, note="Take the boat to Booty Bay (26.33, 73.49)" },
    { type="TURNIN", title="Goblin Sponsorship", questId=1180, coords={ x=26.33, y=73.49 }, npc = { name="Wharfmaster Lozgil" }, note="Wharfmaster Lozgil in Booty Bay (26.33, 73.49)" },
    { type="ACCEPT", title="Goblin Sponsorship", questId=1181, coords={ x=26.33, y=73.49 }, npc = { name="Wharfmaster Lozgil" }, note="Wharfmaster Lozgil in Booty Bay (26.33, 73.49)" },
    { type="SET_HEARTH", title="Booty Bay", coords={ x=27.1, y=77.3 }, npc = { name="Innkeeper Skindle" }, note="Speak to Innkeeper Skindle and set hearth to Booty Bay (27.1, 77.3)" },
    { type="ACCEPT", title="Singing Blue Shards", questId=605, coords={ x=27.1, y=77.29 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.10, 77.29)" },
    { type="ACCEPT", title="Bloodscalp Ears", questId=189, coords={ x=27.01, y=77.18 }, npc = { name="Kebok" }, note="Kebok in The Salty Sailor Tavern (27.01, 77.18)" },
    { type="ACCEPT", title="Hostile Takeover", questId=213, coords={ x=27.01, y=77.18 }, npc = { name="Kebok" }, note="Kebok in The Salty Sailor Tavern (27.01, 77.18)" },
    { type="ACCEPT", title="Investigate the Camp", questId=201, coords={ x=26.99, y=77.23 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern (26.99, 77.23)" },
    { type="ACCEPT", title="Supply and Demand", questId=575, coords={ x=28.25, y=77.57 }, npc = { name="Drizzlik" }, note="Drizzlik in Booty Bay (28.25, 77.57)" },
    { type="TURNIN", title="Goblin Sponsorship", questId=1181, coords={ x=27.2, y=76.9 }, npc = { name="Baron Revilgaz" }, note="Baron Revilgaz in Booty Bay, 3rd floor of the inn (27.2, 76.9)" },
    { type="ACCEPT", title="Goblin Sponsorship", questId=1182, coords={ x=27.21, y=76.9 }, npc = { name="Baron Revilgaz" }, note="Baron Revilgaz in Booty Bay (27.21, 76.90)" },
    { type="FLIGHTPATH", npc = { name="Gringer" }, coords={ x=26.84, y=77.07 }, note="Speak to Gringer and grab flight path for Booty Bay (26.84, 77.07)" },
    { type="ACCEPT", title="The Defense of Grom'gol", questId=568, coords={ x=32.22, y=28.91 }, npc = { name="Commander Aggro'gosh" }, note="Commander Aggro'gosh in Grom'gol Base Camp (32.22, 28.91)" },
    { type="ACCEPT", title="Mok'thardin's Enchantment", questId=570, coords={ x=32.14, y=29.16 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.14, 29.16)" },
    { type="ACCEPT", title="Hunt for Yenniku", questId=581, coords={ x=32.16, y=27.78 }, npc = { name="Nimboya" }, note="Nimboya in Grom'gol Base Camp (32.16, 27.78)" },
    { type="ACCEPT", title="Trollbane", questId=638, coords={ x=32.16, y=27.78 }, npc = { name="Nimboya" }, note="Nimboya in Grom'gol Base Camp (32.16, 27.78)" },
    { type="ACCEPT", title="Bloody Bone Necklaces", questId=596, coords={ x=32.23, y=27.77 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.23, 27.77)" },
    { type="ACCEPT", title="The Vile Reef", questId=629, coords={ x=32.23, y=27.77 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.23, 27.77)" },
    { type="NOTE", note="Keep any Green Hills of Stranglethorn - Page 1 type pages that you find, it is a random drop from any Humanoids enemies in Stranglethorn Vale. You can also buy or sell these pages for decent profit in the Auction House if you fail to complete it. Tick this step" },
    { type="COMPLETE", title="Singing Blue Shards", questId=605, coords={ x=37.0, y=8.0 }, note="Find Stone Maw Basilisk and collect some Singing Crystal Shard, you can complete this later, tick this step if you can't find crocs The Savage Coast (37, 8)" },
    { type="TRAVEL", coords={ x=29.52, y=20.87 }, note="Travel to Bal'lal Ruins (29.52, 20.87)" },
    { type="COMPLETE", title="Bloodscalp Ears", questId=189, coords={ x=29.52, y=20.87 }, note="Kill the Bloodscalp trolls and collect 15 Bloodscalp Ear in Bal'lal Ruins (29.52, 20.87)" },
    { type="COMPLETE", title="Hunt for Yenniku", questId=581, coords={ x=29.0, y=19.61 }, note="Kill Bloodscalp trolls and collect 9 Bloodscalp Tusk in Bal'lal Ruins (29.00, 19.61)" },
    { type="TRAVEL", coords={ x=34.0, y=19.0 }, note="Travel to Stranglethorn Vale (34, 19)" },
    { type="COMPLETE", title="Tiger Mastery", questId=187, coords={ x=34.0, y=19.0 }, note="Kill 10 Elder Stranglethorn Tiger between the troll ruins and Nessingwary's camp (34, 19)" },
    { type="COMPLETE", title="Raptor Mastery", questId=195, coords={ x=38.0, y=23.0 }, note="Kill 10 Lashtail Raptor near Grom'gol Base Camp (38, 23)" },
    { type="COMPLETE", title="The Defense of Grom'gol", questId=568, coords={ x=38.0, y=23.0 }, note="Kill 15 Lashtail Raptor in Stranglethorn Vale (38, 23)" },
    { type="TRAVEL", coords={ x=32.16, y=27.78 }, note="Travel to Grom'gol Base Camp (32.16, 27.78)" },
    { type="TURNIN", title="Hunt for Yenniku", questId=581, coords={ x=32.16, y=27.78 }, npc = { name="Nimboya" }, note="Nimboya in Grom'gol Base Camp (32.16, 27.78)" },
    { type="ACCEPT", title="Headhunting", questId=582, coords={ x=32.16, y=27.78 }, npc = { name="Nimboya" }, note="Nimboya in Grom'gol Base Camp (32.16, 27.78)" },
    { type="TURNIN", title="The Defense of Grom'gol", questId=568, coords={ x=32.22, y=28.91 }, npc = { name="Commander Aggro'gosh" }, note="Commander Aggro'gosh in Grom'gol Base Camp (32.22, 28.91)" },
    { type="ACCEPT", title="The Defense of Grom'gol", questId=569, coords={ x=32.22, y=28.91 }, npc = { name="Commander Aggro'gosh" }, note="Commander Aggro'gosh in Grom'gol Base Camp (32.22, 28.91)" },
    { type="COMPLETE", title="Headhunting", questId=582, coords={ x=24.65, y=9.95 }, note="Follow the path and kill Bloodscalp Headhunter in Ruins of Zul'Kunda 20 Shrunken Head. Note: only Bloodscalp Headhunter will drop the item (24.65, 9.95) (27.52, 9.58) (27.52, 9.58) (27.24, 10.24) (26.56, 8.31) (26.28, 7.95) (24.75, 8.03)" },
    { type="COMPLETE", title="Bloody Bone Necklaces", questId=596, coords={ x=19.0, y=14.0 }, note="Kill Trolls in the Zuuldaia Ruins to collect 25 Bloody Bone Necklace (19, 14)" },
    { type="TRAVEL", coords={ x=35.26, y=11.12 }, note="Travel to Nesingwary's Expedition (35.26, 11.12)" },
    { type="COMPLETE", title="Investigate the Camp", questId=201, coords={ x=35.26, y=11.12 }, note="in Nesingwary's Expedition (35.26, 11.12)" },
    { type="TURNIN", title="Raptor Mastery", questId=195, coords={ x=35.62, y=10.79 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.62, 10.79)" },
    { type="ACCEPT", title="Raptor Mastery", questId=196, coords={ x=35.62, y=10.79 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.62, 10.79)" },
    { type="TURNIN", title="Hemet Nesingwary Jr.", questId=5762, coords={ x=35.62, y=10.79 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.62, 10.79)" },
    { type="TURNIN", title="Hunting in Stranglethorn", questId=5763, coords={ x=35.62, y=10.79 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.62, 10.79)" },
    { type="ACCEPT", title="Panther Mastery", questId=192, coords={ x=35.59, y=10.58 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.59, 10.58)" },
    { type="COMPLETE", title="Singing Blue Shards", questId=605, coords={ x=24.22, y=17.65 }, note="Find Crystal Spine Basilisk and collect some Singing Crystal Shard in The Savage Coast, tick this step if you can't find anymore crocs (24.22, 17.65)" },
    { type="COMPLETE", title="Tiger Mastery", questId=188, coords={ x=31.86, y=17.32 }, note="Kill Sin'Dall who is on top of a nearby hill and collect Paw of Sin'Dall (31.86, 17.32)" },
    { type="TURNIN", title="Tiger Mastery", questId=188, coords={ x=35.61, y=10.66 }, npc = { name="Ajeck Rouack" }, note="Ajeck Rouack in Nesingwary's Expedition (35.61, 10.66)" },
    { type="COMPLETE", title="Supply and Demand", questId=575, coords={ x=34.82, y=10.4 }, note="Kill River Crocolisk and collect 2 Large River Crocolisk Skin in Nesingwary's Expedition (34.82, 10.40)" },
    { type="TRAVEL", coords={ x=42.48, y=18.47 }, note="Travel to Venture Co. Operations Center (42.48, 18.47)" },
    { type="NOTE", note="Kill Venture Co. Geologist and collect 8 Tumbled Crystal in Venture Co. Base Camp" },
    { type="COMPLETE", title="Foreman Cozzle", questId=1182, coords={ x=42.48, y=18.47 }, note="Kill Foreman Cozzle to collect Cozzle's Key in Venture Co. Operations Center (42.48, 18.47) | Use Cozzle's Key to open Cozzle's Footlocker and get Fuel Regulator Blueprints (43, 20)" },
    { type="TRAVEL", coords={ x=44.57, y=20.58 }, note="Travel to Venture Co. Base Camp (44.57, 20.58)" },
    { type="COMPLETE", title="Hostile Takeover", questId=213, coords={ x=44.57, y=20.58 }, note="Kill Venture Co. Geologist and collect 8 Tumbled Crystal from in Venture Co. Base Camp (44.57, 20.58)" },
    { type="COMPLETE", title="Mok'thardin's Enchantment", questId=570, coords={ x=48.0, y=21.0 }, note="Kill Shadowmaw Panther to collect 8 Shadowmaw Claw and kill Stranglethorn Tigress to collect a Pristine Tigress Fang (48, 21)" },
    { type="TRAVEL", coords={ x=48.0, y=21.0 }, note="Travel to Stranglethorn Vale (48, 21) (38, 37)" },
    { type="COMPLETE", title="Panther Mastery", questId=192, coords={ x=48.0, y=21.0 }, note="Kill 10 Shadowmaw Panther in Stranglethorn Vale (48, 21) (38, 37)" },
    { type="COMPLETE", title="Singing Blue Shards", questId=605, coords={ x=24.22, y=17.65 }, note="Find Crystal Spine Basilisk or Stone Maw Basilisk and collect 10 Singing Crystal Shard in The Savage Coast (24.22, 17.65) (37, 8)" },
    { type="TRAVEL", coords={ x=36.93, y=30.82 }, note="Travel to Mizjah Ruins (36.93, 30.82)" },
    { type="COMPLETE", title="The Defense of Grom'gol", questId=569, coords={ x=36.0, y=30.0 }, note="Kill 10 Mosh'Ogg Brute and 5 Mosh'Ogg Witch Doctor southeast of Grom'gol at the Mizjah Ruins (36, 30)" },
    { type="TRAVEL", coords={ x=35.53, y=10.56 }, note="Travel to Nesingwary's Expedition (35.53, 10.56)" },
    { type="TURNIN", title="Panther Mastery", questId=192, coords={ x=35.53, y=10.56 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.53, 10.56)" },
    { type="ACCEPT", title="Panther Mastery", questId=193, coords={ x=35.53, y=10.56 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.53, 10.56)" },
    { type="TRAVEL", coords={ x=27.1, y=77.29 }, note="Travel to The Salty Sailor Tavern (27.10, 77.29)" },
    { type="TURNIN", title="Singing Blue Shards", questId=605, coords={ x=27.1, y=77.29 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.10, 77.29)" },
    { type="TURNIN", title="Bloodscalp Ears", questId=189, coords={ x=27.01, y=77.18 }, npc = { name="Kebok" }, note="Kebok in The Salty Sailor Tavern (27.01, 77.18)" },
    { type="ACCEPT", title="Skullsplitter Tusks", questId=209, coords={ x=26.99, y=77.13 }, npc = { name="Kebok" }, note="Kebok in The Salty Sailor Tavern (26.99, 77.13)" },
    { type="TURNIN", title="Hostile Takeover", questId=213, coords={ x=27.01, y=77.18 }, npc = { name="Kebok" }, note="Kebok in The Salty Sailor Tavern (27.01, 77.18)" },
    { type="TURNIN", title="Investigate the Camp", questId=201, coords={ x=26.99, y=77.23 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern (26.99, 77.23)" },
    { type="TURNIN", title="Supply and Demand", questId=575, coords={ x=28.27, y=77.55 }, npc = { name="Drizzlik" }, note="Drizzlik in Booty Bay (28.27, 77.55)" },
    { type="TURNIN", title="Goblin Sponsorship", questId=1182, coords={ x=27.2, y=76.9 }, note="Baron Revilgaz, 3rd floor of the inn (27.2, 76.9)" },
    { type="ACCEPT", title="Goblin Sponsorship", questId=1183, coords={ x=27.21, y=76.9 }, npc = { name="Baron Revilgaz" }, note="Baron Revilgaz in Booty Bay (27.21, 76.90)" },
    { type="TRAVEL", coords={ x=35.61, y=10.66 }, note="Travel to Nesingwary's Expedition (35.61, 10.66)" },
    { type="TURNIN", title="Tiger Mastery", questId=187, coords={ x=35.61, y=10.66 }, npc = { name="Ajeck Rouack" }, note="Ajeck Rouack in Nesingwary's Expedition (35.61, 10.66)" },
    { type="ACCEPT", title="Tiger Mastery", questId=188, coords={ x=35.61, y=10.66 }, npc = { name="Ajeck Rouack" }, note="Ajeck Rouack in Nesingwary's Expedition (35.61, 10.66)" },
    { type="TRAVEL", coords={ x=32.18, y=28.82 }, note="Travel to Grom'gol Base Camp (32.18, 28.82)" },
    { type="TURNIN", title="The Defense of Grom'gol", questId=569, coords={ x=32.18, y=28.82 }, npc = { name="Commander Aggro'gosh" }, note="Commander Aggro'gosh in Grom'gol Base Camp (32.18, 28.82)" },
    { type="TURNIN", title="Mok'thardin's Enchantment", questId=570, coords={ x=32.14, y=29.16 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.14, 29.16)" },
    { type="ACCEPT", title="Mok'thardin's Enchantment", questId=572, coords={ x=32.14, y=29.16 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.14, 29.16)" },
    { type="TURNIN", title="Headhunting", questId=582, coords={ x=32.16, y=27.78 }, npc = { name="Nimboya" }, note="Nimboya in Grom'gol Base Camp (32.16, 27.78)" },
    { type="TURNIN", title="Bloody Bone Necklaces", questId=596, coords={ x=32.23, y=27.77 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.23, 27.77)" },
    { type="ACCEPT", title="Trollbane", questId=638, coords={ x=32.17, y=27.71 }, npc = { name="Nimboya" }, note="Nimboya in Grom'gol Base Camp (32.17, 27.71)" },
    { type="TRAVEL", coords={ x=28.11, y=76.13 }, note="Travel to Booty Bay (28.11, 76.13)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=595, coords={ x=28.11, y=76.13 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.11, 76.13)" },
    { type="ACCEPT", title="Scaring Shaky", questId=606, coords={ x=27.76, y=77.12 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.76, 77.12)" },
    { type="SET_HEARTH", title="Booty Bay", coords={ x=27.1, y=77.3 }, npc = { name="Innkeeper Skindle" }, note="Speak to Innkeeper Skindle and set hearth to Booty Bay (27.1, 77.3)" },
    { type="TURNIN", title="The Rumormonger", questId=1115, coords={ x=26.98, y=77.23 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern (26.98, 77.23)" },
    { type="ACCEPT", title="Dream Dust in the Swamp", questId=1116, coords={ x=26.98, y=77.23 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern (26.98, 77.23)" },
    { type="TURNIN", title="Sunken Treasure", questId=669, coords={ x=27.17, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.17, 77.00)" },
    { type="ACCEPT", title="Sunken Treasure", questId=670, coords={ x=27.17, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.17, 77.00)" },
    { type="TRAVEL", coords={ x=32.26, y=27.71 }, note="Travel to Grom'gol Base Camp (32.26, 27.71)" },
    { type="TURNIN", title="The Troll Witchdoctor", questId=1240, coords={ x=32.26, y=27.71 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.26, 27.71)" },
    { type="ACCEPT", title="Marg Speaks", questId=1261, coords={ x=32.2, y=27.7 }, npc = { name="Bubbling Cauldron" }, note="Bubbling Cauldron in Grom'gol Base Camp (32.2, 27.7)" },
    { type="TRAVEL", coords={ x=31.0, y=41.0 }, note="Travel to Gurubashi Arena (31, 41)" },
    { type="COMPLETE", title="Mok'thardin's Enchantment", questId=572, coords={ x=31.0, y=41.0 }, note="Kill Jungle Stalker for 10 Jungle Stalker Feather in Gurubashi Arena (31, 41)" },
    { type="COMPLETE", title="Raptor Mastery", questId=196, coords={ x=31.51, y=42.33 }, note="Kill 10 Jungle Stalker in Gurubashi Arena (31.51, 42.33)" },
    { type="TRAVEL", coords={ x=32.16, y=29.18 }, note="Travel to Grom'gol Base Camp (32.16, 29.18)" },
    { type="TURNIN", title="Mok'thardin's Enchantment", questId=572, coords={ x=32.16, y=29.18 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.16, 29.18)" },
    { type="ACCEPT", title="Mok'thardin's Enchantment", questId=571, coords={ x=32.16, y=29.18 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.16, 29.18)" },
    { type="TRAVEL", coords={ x=27.22, y=28.89 }, note="Travel to The Vile Reef (27.22, 28.89)" },
    { type="COMPLETE", title="The Vile Reef", questId=629, coords={ x=27.22, y=28.89 }, note="Click on Gri'lek the Wanderer tablet to collect Tablet Shard in The Vile Reef (27.22, 28.89) (24.72, 22.29) (24.75, 22.80)" },
    { type="COMPLETE", title="Encrusted Tail Fins", questId=1107, coords={ x=24.0, y=24.0 }, note="Kill Saltscale Warrior, Saltscale Oracle, Saltscale Hunter and Saltscale Forager to collect 10 Encrusted Tail Fin (24, 24)" },
    { type="TRAVEL", coords={ x=32.22, y=27.77 }, note="Travel to Grom'gol Base Camp (32.22, 27.77)" },
    { type="TURNIN", title="The Vile Reef", questId=629, coords={ x=32.22, y=27.77 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.22, 27.77)" },
    { type="COMPLETE", title="Some Assembly Required", questId=577, coords={ x=38.35, y=32.58 }, note="Kill Snapjaw Crocolisk collect 5 Snapjaw Crocolisk Skin along the river (38.35, 32.58) (40.46, 25.35) (38.27, 32.18)" },
    { type="TRAVEL", coords={ x=42.17, y=36.16 }, note="Travel to Ziata'jai Ruins (42.17, 36.16)" },
    { type="COMPLETE", title="Skullsplitter Tusks", questId=209, coords={ x=45.72, y=42.19 }, note="Kill Trolls and collect 18 Skullsplitter Tusk in Ziata'jai Ruins and Ruins of Zul'Mamwe. Stick to this area for the lower level trolls (45.72, 42.19) (44.86, 40.70)" },
    { type="COMPLETE", title="Panther Mastery", questId=193, coords={ x=48.35, y=23.74 }, note="Kill Bhag'thera and loot the Fang of Bhag'thera, you will need to group with at least one other player for this. (48.35, 23.74)" },
    { type="TRAVEL", coords={ x=35.58, y=10.59 }, note="Travel to Nesingwary's Expedition (35.58, 10.59)" },
    { type="TURNIN", title="Panther Mastery", questId=193, coords={ x=35.58, y=10.59 }, npc = { name="Erlgadin" }, note="Sir S. J. Erlgadin in Nesingwary's Expedition (35.58, 10.59)" },
    { type="TURNIN", title="Raptor Mastery", questId=196, coords={ x=35.65, y=10.75 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.75)" },
    { type="ACCEPT", title="Raptor Mastery", questId=197, coords={ x=35.65, y=10.75 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.75)" },
    { type="TRAVEL", coords={ x=27.23, y=69.54 }, note="Travel to Southern Savage Coast (27.23, 69.54)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=595, coords={ x=27.23, y=69.54 }, npc = { name="Bloodsail Correspondence" }, note="Bloodsail Correspondence in Southern Savage Coast (27.23, 69.54)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=597, coords={ x=27.23, y=69.54 }, npc = { name="Bloodsail Correspondence" }, note="Bloodsail Correspondence in Southern Savage Coast (27.23, 69.54)" },
    { type="TRAVEL", coords={ x=30.94, y=71.69 }, note="Travel to Mistvale Valley (30.94, 71.69) (33.06, 67.08)" },
    { type="COMPLETE", title="Scaring Shaky", questId=606, coords={ x=33.52, y=63.04 }, note="Kill the Elder Mistvale Gorilla for 5 Mistvale Giblets in the Mistvale Valley (33.52, 63.04)" },
    { type="COMPLETE", title="Mok'thardin's Enchantment", questId=571, coords={ x=34.0, y=64.0 }, note="Kill Elder Mistvale Gorilla in the Mistvale Valley until you find the Aged Gorilla Sinew. Note: Save all the Gorilla Fang you find for a later quest (34, 64)" },
    { type="TRAVEL", coords={ x=26.9, y=73.62 }, note="Travel to Booty Bay (26.90, 73.62)" },
    { type="TURNIN", title="Scaring Shaky", questId=606, coords={ x=26.9, y=73.62 }, npc = { name="Phillipe" }, note="\\Shaky\\ Phillipe in Booty Bay (26.90, 73.62)" },
    { type="ACCEPT", title="Return to MacKinley", questId=607, coords={ x=26.9, y=73.62 }, npc = { name="Phillipe" }, note="\\Shaky\\ Phillipe in Booty Bay (26.90, 73.62)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=597, coords={ x=28.11, y=76.13 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.11, 76.13)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=599, coords={ x=28.11, y=76.13 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.11, 76.13)" },
    { type="TURNIN", title="Return to MacKinley", questId=607, coords={ x=27.76, y=77.12 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.76, 77.12)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=599, coords={ x=27.14, y=76.96 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.14, 76.96)" },
    { type="TURNIN", title="Skullsplitter Tusks", questId=209, coords={ x=27.01, y=77.14 }, npc = { name="Kebok" }, note="Kebok in The Salty Sailor Tavern (27.01, 77.14)" },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 1. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 4. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 6. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 8. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 10. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 11. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 14. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 16. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 18. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 20. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 21. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 24. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 25. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 26. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 27. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="TRAVEL", coords={ x=32.16, y=29.18 }, note="Travel to Grom'gol Base Camp (32.16, 29.18)" },
    { type="TURNIN", title="Mok'thardin's Enchantment", questId=571, coords={ x=32.16, y=29.18 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.16, 29.18)" },
    { type="ACCEPT", title="Mok'thardin's Enchantment", questId=573, coords={ x=32.16, y=29.18 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.16, 29.18)" },
    { type="ACCEPT", title="Split Bone Necklace", questId=598, coords={ x=32.21, y=27.74 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.21, 27.74)" },
    { type="SET_HEARTH", title="Grom'gol Base Camp", coords={ x=31.5, y=29.7 }, npc = { name="Innkeeper Thulbek" }, note="Speak to Innkeeper Thulbek and set hearth to Grom'gol Base Camp (31.5, 29.7)" },
    { type="TRAVEL", coords={ x=35.65, y=10.51 }, note="Travel to Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter I", questId=339, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter II", questId=340, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter III", questId=341, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter IV", questId=342, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter I", questId=339, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter II", questId=340, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter III", questId=341, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter IV", questId=342, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
