-- =========================
-- QS_Thousand_Needles_37_38.lua
-- Converted from TourGuide format on 2025-08-17 18:59:06
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Thousand_Needles_37_38"] = {
  title    = "Thousand Needles (37-38)",
  next     = "Dustwallow Marsh (38-38)",
  nextKey  = "QS_Dustwallow_Marsh_38_38",
  faction  = "Horde",
  minLevel = 37,
  maxLevel = 38,
  steps = {
    { type="TRAVEL", coords={ x=64.8, y=49.6 }, note="Travel to Undercity (64.8, 49.6)" },
    { type="TURNIN", title="To Steal From Thieves", questId=1164, coords={ x=63.76, y=49.17 }, npc = { name="Genavie Callow" }, note="Genavie Callow in Trade Quarter (63.76, 49.17)" },
    { type="NOTE", note="Withdraw Belgrom's Sealed Note from the bank. Tick this step (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Withdraw Fuel Regulator Blueprints from the bank. Tick this step (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Withdraw Kravel's Parts from the bank. Tick this step (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Store Sample Elven Gem in the bank. Tick this step (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="TRAVEL", coords={ x=22.26, y=54.1 }, note="Travel to Orgrimmar (22.26, 54.10)" },
    { type="TURNIN", title="Alliance Relations", questId=1436, coords={ x=22.26, y=54.1 }, npc = { name="Keldran" }, note="Keldran in Orgrimmar (22.26, 54.10)" },
    { type="TRAVEL", coords={ x=67.6, y=64.0 }, note="Travel to The Shimmering Flats (67.6, 64.0)" },
    { type="TURNIN", title="The Swarm Grows", questId=1146, coords={ x=67.6, y=64.0 }, npc = { name="Moktar Krin" }, note="Moktar Krin in The Shimmering Flats (67.6, 64.0)" },
    { type="ACCEPT", title="The Swarm Grows", questId=1147, coords={ x=67.6, y=64.0 }, npc = { name="Moktar Krin" }, note="Moktar Krin in The Shimmering Flats (67.6, 64.0)" },
    { type="TRAVEL", coords={ x=77.82, y=77.18 }, note="Travel to Mirage Raceway (77.82, 77.18)" },
    { type="ACCEPT", title="A Bump in the Road", questId=1175, coords={ x=81.59, y=77.86 }, npc = { name="Trackmaster Zherin" }, note="Trackmaster Zherin in Mirage Raceway (81.59, 77.86)" },
    { type="ACCEPT", title="Hardened Shells", questId=1105, coords={ x=78.14, y=77.07 }, npc = { name="Wizzle Brassbolts" }, note="Wizzle Brassbolts in Mirage Raceway (78.14, 77.07)" },
    { type="ACCEPT", title="Load Lightening", questId=1176, coords={ x=80.14, y=75.86 }, npc = { name="Pozzik" }, note="Pozzik in Mirage Raceway (80.14, 75.86)" },
    { type="ACCEPT", title="Rocket Car Parts", questId=1110, coords={ x=77.82, y=77.18 }, npc = { name="Kravel Koalbeard" }, note="Kravel Koalbeard in Mirage Raceway (77.82, 77.18)" },
    { type="ACCEPT", title="Salt Flat Venom", questId=1104, coords={ x=78.04, y=77.08 }, npc = { name="Fizzle Brassbolts" }, note="Fizzle Brassbolts in Mirage Raceway (78.04, 77.08)" },
    { type="NOTE", note="Collect 30 Rocket Car Parts through out The Shimmering Flats. You can complete the quests below in any order, click on the green button to switch quest waypoints and targets" },
    { type="COMPLETE", title="Salt Flat Venom", questId=1104, coords={ x=72.0, y=75.0 }, note="Kill Scorpid Reaver and Scorpid Terror in The Shimmering Flats for 6 Salty Scorpid Venom (72, 75)" },
    { type="COMPLETE", title="Hardened Shells", questId=1105, coords={ x=82.0, y=54.0 }, note="Kill Sparkleshell Tortoise, Sparkleshell Snapper and Sparkleshell Borer in The Shimmering Flats for 9 Hardened Tortoise Shell (82, 54)" },
    { type="COMPLETE", title="Load Lightening", questId=1176, coords={ x=87.0, y=66.0 }, note="Kill Salt Flats Scavenger and Salt Flats Vulture for 10 Hollow Vulture Bone in The Shimmering Flats (87, 66)" },
    { type="COMPLETE", title="A Bump in the Road", questId=1175, coords={ x=76.0, y=87.0 }, note="Kill the required Saltstone crocs, Saltstone Gazer are found bottom part of the map and Saltstone Basilisk are found top of the map (76, 87) (86.4, 60.1) (73, 59)" },
    { type="TRAVEL", coords={ x=88.0, y=75.0 }, note="Travel to The Shimmering Flats (88, 75)" },
    { type="COMPLETE", title="Rocket Car Parts", questId=1110, coords={ x=87.0, y=77.0 }, note="Collect 30 Rocket Car Parts through out The Shimmering Flats (87, 77) (86, 60) (77.5, 54) (70, 62) (72, 78) (78, 85)" },
    { type="TURNIN", title="Rocket Car Parts", questId=1110, coords={ x=77.85, y=77.22 }, npc = { name="Kravel Koalbeard" }, note="Kravel Koalbeard in Mirage Raceway (77.85, 77.22)" },
    { type="ACCEPT", title="Wharfmaster Dizzywig", questId=1111, coords={ x=77.85, y=77.22 }, npc = { name="Kravel Koalbeard" }, note="Kravel Koalbeard in Mirage Raceway (77.85, 77.22)" },
    { type="ACCEPT", title="Hemet Nesingwary", questId=5762, coords={ x=77.85, y=77.22 }, npc = { name="Kravel Koalbeard" }, note="Kravel Koalbeard in Mirage Raceway (77.85, 77.22)" },
    { type="TURNIN", title="Salt Flat Venom", questId=1104, coords={ x=78.01, y=77.04 }, npc = { name="Fizzle Brassbolts" }, note="Fizzle Brassbolts in Mirage Raceway (78.01, 77.04)" },
    { type="TURNIN", title="Hardened Shells", questId=1105, coords={ x=78.12, y=77.01 }, npc = { name="Wizzle Brassbolts" }, note="Wizzle Brassbolts in Mirage Raceway (78.12, 77.01)" },
    { type="TURNIN", title="Load Lightening", questId=1176, coords={ x=80.13, y=75.87 }, npc = { name="Pozzik" }, note="Pozzik in Mirage Raceway (80.13, 75.87)" },
    { type="ACCEPT", title="Goblin Sponsorship", questId=1178, coords={ x=80.13, y=75.87 }, npc = { name="Pozzik" }, note="Pozzik in Mirage Raceway (80.13, 75.87)" },
    { type="TURNIN", title="A Bump in the Road", questId=1175, coords={ x=81.59, y=77.93 }, npc = { name="Trackmaster Zherin" }, note="Trackmaster Zherin in Mirage Raceway (81.59, 77.93)" },
    { type="ACCEPT", title="Martek the Exiled", questId=1106, coords={ x=78.04, y=77.08 }, npc = { name="Fizzle Brassbolts" }, note="Fizzle Brassbolts in Mirage Raceway (78.04, 77.08)" },
    { type="ACCEPT", title="Encrusted Tail Fins", questId=1107, coords={ x=78.14, y=77.07 }, npc = { name="Wizzle Brassbolts" }, note="Wizzle Brassbolts in Mirage Raceway (78.14, 77.07)" },
    { type="TURNIN", title="Parts for Kravel", questId=1112, coords={ x=77.8, y=77.2 }, npc = { name="Kravel Koalbeard" }, note="Kravel Koalbeard in Mirage Raceway (77.8, 77.2)" },
    { type="ACCEPT", title="Delivery to the Gnomes", questId=1114, coords={ x=77.8, y=77.2 }, npc = { name="Kravel Koalbeard" }, note="Kravel Koalbeard in Mirage Raceway (77.8, 77.2)" },
    { type="TURNIN", title="Delivery to the Gnomes", questId=1114, coords={ x=78.0, y=77.1 }, npc = { name="Fizzle Brassbolts" }, note="Fizzle Brassbolts in Mirage Raceway (78.0, 77.1)" },
    { type="TURNIN", title="Goblin Sponsorship", questId=1183, coords={ x=80.1, y=75.9 }, npc = { name="Pozzik" }, note="Pozzik in Mirage Raceway (80.1, 75.9)" },
    { type="ACCEPT", title="The Eighteenth Pilot", questId=1186, coords={ x=80.1, y=75.9 }, npc = { name="Pozzik" }, note="Pozzik in Mirage Raceway (80.1, 75.9)" },
    { type="TURNIN", title="The Eighteenth Pilot", questId=1186, coords={ x=80.3, y=76.1 }, npc = { name="Razzeric" }, note="Razzeric in Mirage Raceway (80.3, 76.1)" },
    { type="ACCEPT", title="Razzeric's Tweaking", questId=1187, coords={ x=80.3, y=76.1 }, npc = { name="Razzeric" }, note="Razzeric in Mirage Raceway (80.3, 76.1)" },
    { type="TURNIN", title="Encrusted Tail Fins", questId=1107, coords={ x=78.1, y=77.1 }, npc = { name="Wizzle Brassbolts" }, note="Wizzle Brassbolts in Mirage Raceway (78.1, 77.1)" },
    { type="ACCEPT", title="The Rumormonger", questId=1115, coords={ x=77.8, y=77.2 }, npc = { name="Kravel Koalbeard" }, note="Kravel Koalbeard in Mirage Raceway (77.8, 77.2)" },
    { type="NOTE", note="Kill Silithids enemies until you find Cracked Silithid Carapace (68, 80)", coords={ x=68.0, y=80.0 } },
    { type="ACCEPT", title="Parts of the Swarm", questId=1148, note="Use Cracked Silithid Carapace to accept the quest" },
    { type="COMPLETE", title="Parts of the Swarm", questId=1148, coords={ x=69.0, y=85.0 }, note="Kill Silithids to collect 1 Silithid Heart, 5 Silithid Talon and 3 Intact Silithid Carapace (69, 85)" },
    { type="COMPLETE", title="The Swarm Grows", questId=1147, coords={ x=69.0, y=85.0 }, note="Kill 5 Silithid Searcher, 5 Silithid Hive Drone and 5 Silithid Invader (69, 85)" },
    { type="TRAVEL", coords={ x=67.6, y=64.0 }, note="Travel to Mirage Raceway (67.6, 64.0)" },
    { type="TURNIN", title="The Swarm Grows", questId=1147, coords={ x=67.6, y=64.0 }, npc = { name="Moktar Krin" }, note="Moktar Krin in Mirage Raceway (67.6, 64.0)" },
    { type="TRAVEL", coords={ x=51.1, y=29.6 }, note="Travel to The Crossroads (51.1, 29.6)" },
    { type="TURNIN", title="Parts of the Swarm", questId=1148, coords={ x=51.1, y=29.6 }, npc = { name="Korran" }, note="Korran in The Crossroads (51.1, 29.6)" },
    { type="NOTE", note="Destroy Cracked Silithid Carapace, you no longer need this" },
    { type="ACCEPT", title="Parts of the Swarm", questId=1184, coords={ x=51.1, y=29.6 }, npc = { name="Korran" }, note="Korran in The Crossroads (51.1, 29.6)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
