-- =========================
-- QS_Gilneas_42_43.lua
-- Converted from TourGuide format on 2025-08-17 18:59:06
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Gilneas_42_43"] = {
  title    = "Gilneas (42-43)",
  next     = "Stranglethorn (42-43)",
  nextKey  = "QS_Stranglethorn_42_43",
  faction  = "Horde",
  minLevel = 42,
  maxLevel = 43,
  steps = {
    { type="TRAVEL", coords={ x=65.9, y=42.6 }, note="Travel to Undercity (65.9, 42.6)" },
    { type="ACCEPT", title="To Gilneas", questId=40850, coords={ x=65.9, y=42.6 }, note="Dark Ranger Anya under Undercity Bank (65.9, 42.6)" },
    { type="TRAVEL", coords={ x=47.2, y=16.0 }, note="Travel to The Greymane Wall in Silverpine Forest (47.2, 16.0)" },
    { type="TRAVEL", coords={ x=14.5, y=35.5 }, note="Travel to Blackthorn's Camp in western Gilneas (14.5, 35.5)" },
    { type="TURNIN", title="To Gilneas", questId=40850, coords={ x=14.0, y=33.7 }, npc = { name="Blackthorn" }, note="Blackthorn in Blackthorn's Camp (14.0, 33.7)" },
    { type="ACCEPT", title="Report to Livia Strongarm", questId=40846, coords={ x=14.0, y=33.7 }, npc = { name="Blackthorn" }, note="Blackthorn in Blackthorn's Camp (14.0, 33.7)" },
    { type="ACCEPT", title="Report to Luke Agamand", questId=40844, coords={ x=14.0, y=33.7 }, npc = { name="Blackthorn" }, note="Blackthorn in Blackthorn's Camp (14.0, 33.7)" },
    { type="TURNIN", title="Report to Luke Agamand", questId=40844, coords={ x=14.1, y=33.7 }, npc = { name="Luke Agamand" }, note="Luke Agamand in Blackthorn's Camp (14.1, 33.7)" },
    { type="ACCEPT", title="Heist in Dryrock Mine", questId=40845, coords={ x=14.1, y=33.7 }, npc = { name="Luke Agamand" }, note="Luke Agamand in Blackthorn's Camp (14.1, 33.7)" },
    { type="ACCEPT", title="Forsaken at the Church", questId=40851, coords={ x=14.1, y=33.7 }, npc = { name="Luke Agamand" }, note="Luke Agamand in Blackthorn's Camp (14.1, 33.7)" },
    { type="NOTE", note="Optional quest to be completed in Gilneas City dungeon" },
    { type="TURNIN", title="Report to Livia Strongarm", questId=40846, coords={ x=14.1, y=34.3 }, npc = { name="Livia Strongarmdd" }, note="Livia Strongarmdd in Blackthorn's Camp (14.1, 34.3)" },
    { type="ACCEPT", title="Rendezvous with the Infiltrator", questId=40847, coords={ x=14.1, y=34.3 }, npc = { name="Livia Strongarmdd" }, note="Livia Strongarmdd in Blackthorn's Camp (14.1, 34.3)" },
    { type="COMPLETE", title="Heist in Dryrock Mine", questId=40845, coords={ x=21.2, y=51.5 }, note="Collect 16 Sacks of Mithril Ore from the mine uphill (21.2, 51.5)" },
    { type="NOTE", note="Watch out! There is high level elite near the inn where Greta is standing." },
    { type="COMPLETE", title="Rendezvous with the Infiltrator", questId=40847, coords={ x=14.1, y=34.3 }, note="Get the report from Greta south of Ruins of Greyshire (14.1, 34.3)" },
    { type="ACCEPT", title="Greymane Hatred", questId=40980, coords={ x=38.1, y=60.8 }, note="Harrison Blackheart south-east from Ruins of Greyshire (38.1, 60.8)" },
    { type="COMPLETE", title="Greymane Hatred", questId=40980, coords={ x=19.9, y=60.9 }, note="Collect 40 Greymane Signets from soldiers to the west (19.9, 60.9)" },
    { type="TURNIN", title="Heist in Dryrock Mine", questId=40845, coords={ x=14.1, y=33.7 }, npc = { name="Luke Agamand" }, note="Luke Agamand in Blackthorn's Camp (14.1, 33.7)" },
    { type="TURNIN", title="Rendezvous with the Infiltrator", questId=40847, coords={ x=14.1, y=34.3 }, npc = { name="Livia Strongarmdd" }, note="Livia Strongarmdd in Blackthorn's Camp (14.1, 34.3)" },
    { type="ACCEPT", title="Quality Time with Blackthorn", questId=40848, coords={ x=14.0, y=33.7 }, npc = { name="Blackthorn" }, note="Blackthorn in Blackthorn's Camp (14.0, 33.7)" },
    { type="COMPLETE", title="Quality Time with Blackthorn", questId=40848, coords={ x=11.9, y=39.0 }, note="Kill 8 Spitecrest Netters on west shore (11.9, 39.0)" },
    { type="TURNIN", title="Quality Time with Blackthorn", questId=40848, coords={ x=14.0, y=33.7 }, npc = { name="Blackthorn" }, note="Blackthorn in Blackthorn's Camp (14.0, 33.7)" },
    { type="NOTE", note="Optional quest to be completed in Gilneas City dungeon" },
    { type="TURNIN", title="Greymane Hatred", questId=40980, coords={ x=38.1, y=60.8 }, note="Harrison Blackheart south-east from Ruins of Greyshire (38.1, 60.8)" },
    { type="ACCEPT", title="The Blackheart Killer", questId=40981, coords={ x=38.1, y=60.8 }, note="Harrison Blackheart south-east from Ruins of Greyshire (38.1, 60.8)" },
    { type="TRAVEL", coords={ x=56.9, y=38.1 }, note="Travel north-east to the church (56.9, 38.1)" },
    { type="ACCEPT", title="Revenge After Death", questId=40974, coords={ x=56.6, y=39.6 }, npc = { name="Dominic Larson" }, note="Dominic Larson in Stillward Church (56.6, 39.6)" },
    { type="ACCEPT", title="War on Worgen", questId=40976, coords={ x=56.9, y=39.4 }, npc = { name="Deathstalker Vernon" }, note="Deathstalker Vernon in Stillward Church (56.9, 39.4)" },
    { type="ACCEPT", title="A Chief Among Brutes", questId=40855, coords={ x=56.9, y=39.4 }, npc = { name="Deathstalker Vernon" }, note="Deathstalker Vernon in Stillward Church (56.9, 39.4)" },
    { type="ACCEPT", title="Vernon's Task", questId=40854, coords={ x=56.9, y=39.4 }, npc = { name="Deathstalker Vernon" }, note="Deathstalker Vernon in Stillward Church (56.9, 39.4)" },
    { type="ACCEPT", title="Dead Until Dark", questId=40877, coords={ x=57.3, y=39.6 }, npc = { name="Deathstalker Alynna" }, note="Deathstalker Alynna in Stillward Church (57.3, 39.6)" },
    { type="ACCEPT", title="Foulhide Mongrels", questId=40992, coords={ x=57.5, y=39.8 }, npc = { name="Harlan Ballow" }, note="Harlan Ballow in Stillward Church (57.5, 39.8)" },
    { type="TURNIN", title="Forsaken at the Church", questId=40851, coords={ x=57.7, y=39.6 }, npc = { name="Dark Bishop Mordren" }, note="Dark Bishop Mordren in Stillward Church (57.7, 39.6)" },
    { type="NOTE", note="Optional quest to be completed in Badlands" },
    { type="NOTE", note="Optional quest to be completed in Desolace" },
    { type="SET_HEARTH", title="Stillward Church", coords={ x=57.7, y=39.6 }, npc = { name="Dark Bishop Mordren" }, note="Speak to Dark Bishop Mordren and set hearthstone (57.7, 39.6)" },
    { type="FLIGHTPATH", npc = { name="Andana" }, coords={ x=57.1, y=38.4 }, note="Speak to Andana and grab flight path for Stillward Church (57.1, 38.4)" },
    { type="TRAVEL", coords={ x=49.6, y=31.1 }, note="Travel to Ebonmere Farm, north-west of Stillward Church (49.6, 31.1)" },
    { type="ACCEPT", title="Ebonmere Worgen Infestation", questId=40978, coords={ x=49.6, y=31.1 }, npc = { name="Joshua Ebonmere" }, note="Joshua Ebonmere in Ebonmere Farm (49.6, 31.1)" },
    { type="ACCEPT", title="Ebonmere Bat Infestation", questId=40977, coords={ x=49.6, y=31.1 }, npc = { name="Joshua Ebonmere" }, note="Joshua Ebonmere in Ebonmere Farm (49.6, 31.1)" },
    { type="COMPLETE", title="Ebonmere Bat Infestation", questId=40977, note="Kill 12 bats around the farm" },
    { type="TURNIN", title="Ebonmere Bat Infestation", questId=40977, coords={ x=49.6, y=31.1 }, npc = { name="Joshua Ebonmere" }, note="Joshua Ebonmere in Ebonmere Farm (49.6, 31.1)" },
    { type="COMPLETE", title="Revenge After Death", questId=40974, coords={ x=41.1, y=40.7 }, note="Kill elite Snarlclaw in the cave west of the farm for his paw (41.1, 40.7)" },
    { type="COMPLETE", title="Ebonmere Worgen Infestation", questId=40978, coords={ x=41.1, y=40.7 }, note="Kill worgens in the cave and in the north for their pelts (41.1, 40.7)" },
    { type="COMPLETE", title="War on Worgen", questId=40976, coords={ x=41.1, y=40.7 }, note="Kill 9 alpha worgens in the cave (41.1, 40.7)" },
    { type="TURNIN", title="Ebonmere Worgen Infestation", questId=40978, coords={ x=49.6, y=31.1 }, npc = { name="Joshua Ebonmere" }, note="Joshua Ebonmere in Ebonmere Farm (49.6, 31.1)" },
    { type="NOTE", note="Optional quest to be completed in Gilneas City dungeon" },
    { type="TRAVEL", coords={ x=53.4, y=29.1 }, note="Travel to Glaymore Stead, north of Stillward Church (53.4, 29.1)" },
    { type="NOTE", note="Optional quest to be completed in Gilneas City dungeon" },
    { type="TRAVEL", coords={ x=55.4, y=61.4 }, note="Travel to Brol'ok Mound, south of Stillward Church (55.4, 61.4)" },
    { type="COMPLETE", title="A Chief Among Brutes", questId=40855, coords={ x=56.1, y=55.2 }, note="Kill Chief Maulfist inside the cave for this crown (56.1, 55.2)" },
    { type="COMPLETE", title="Vernon's Task", questId=40854, coords={ x=54.3, y=61.8 }, note="Kill ogres around for their heads (54.3, 61.8)" },
    { type="TRAVEL", coords={ x=44.3, y=66.1 }, note="Travel to Southmire Orchard, west of the cave (44.3, 66.1)" },
    { type="COMPLETE", title="Foulhide Mongrels", questId=40992, coords={ x=44.3, y=66.1 }, note="Kill Foulhides for their Paws (44.3, 66.1)" },
    { type="TRAVEL", coords={ x=34.5, y=49.7 }, note="North-west of the orchard (34.5, 49.7)" },
    { type="TURNIN", title="Dead Until Dark", questId=40877, coords={ x=31.2, y=47.0 }, npc = { name="Orvan Darkeye" }, note="Orvan Darkeye in west Ruins of Greyshire (31.2, 47.0)" },
    { type="ACCEPT", title="All We Need is Blood", questId=40878, coords={ x=31.2, y=47.0 }, npc = { name="Orvan Darkeye" }, note="Orvan Darkeye in west Ruins of Greyshire (31.2, 47.0)" },
    { type="COMPLETE", title="All We Need is Blood", questId=40878, note="Kill bats around" },
    { type="TURNIN", title="All We Need is Blood", questId=40878, coords={ x=31.2, y=47.0 }, npc = { name="Orvan Darkeye" }, note="Orvan Darkeye in west Ruins of Greyshire (31.2, 47.0)" },
    { type="ACCEPT", title="Last of the Living Dead", questId=40879, coords={ x=31.2, y=47.0 }, npc = { name="Orvan Darkeye" }, note="Orvan Darkeye in west Ruins of Greyshire (31.2, 47.0)" },
    { type="COMPLETE", title="Last of the Living Dead", questId=40879, note="Kill undead around" },
    { type="TURNIN", title="Last of the Living Dead", questId=40879, coords={ x=31.2, y=47.0 }, npc = { name="Orvan Darkeye" }, note="Orvan Darkeye in west Ruins of Greyshire (31.2, 47.0)" },
    { type="ACCEPT", title="We Take It From The Living", questId=40880, coords={ x=31.2, y=47.0 }, npc = { name="Orvan Darkeye" }, note="Orvan Darkeye in west Ruins of Greyshire (31.2, 47.0)" },
    { type="TRAVEL", coords={ x=46.2, y=60.1 }, note="Travel east to The Overgrown Acre (46.2, 60.1)" },
    { type="COMPLETE", title="We Take It From The Living", questId=40880, note="Kill Bloodclaws around to get their blood" },
    { type="TRAVEL", note="Very small island on the south-east corner of the zone" },
    { type="COMPLETE", title="The Blackheart Killer", questId=40981, coords={ x=66.7, y=66.4 }, note="Kill Captain Veller to get the necklace (66.7, 66.4)" },
    { type="COMPLETE", title="We Take It From The Living", questId=40880, coords={ x=65.2, y=65.8 }, note="Kill Gilneans around to get their blood (65.2, 65.8)" },
    { type="TURNIN", title="We Take It From The Living", questId=40880, coords={ x=31.2, y=47.0 }, npc = { name="Orvan Darkeye" }, note="Orvan Darkeye in west Ruins of Greyshire (31.2, 47.0)" },
    { type="NOTE", note="Optional quest to be completed in Gilneas City dungeon" },
    { type="TURNIN", title="The Blackheart Killer", questId=40981, coords={ x=38.1, y=60.8 }, note="Harrison Blackheart south-east from Ruins of Greyshire (38.1, 60.8)" },
    { type="ACCEPT", title="In Memory of Franklin", questId=40982, coords={ x=38.1, y=60.8 }, note="Harrison Blackheart south-east from Ruins of Greyshire (38.1, 60.8)" },
    { type="TURNIN", title="In Memory of Franklin", questId=40982, note="Click the grave next to you, then speak with Harrison" },
    { type="TURNIN", title="Revenge After Death", questId=40974, coords={ x=56.6, y=39.6 }, npc = { name="Domindwic Larson" }, note="Domindwic Larson in Stillward Church (56.6, 39.6)" },
    { type="TURNIN", title="War on Worgen", questId=40976, coords={ x=56.9, y=39.4 }, npc = { name="Deathstalker Vernon" }, note="Deathstalker Vernon in Stillward Church (56.9, 39.4)" },
    { type="TURNIN", title="A Chief Among Brutes", questId=40855, coords={ x=56.9, y=39.4 }, npc = { name="Deathstalker Vernon" }, note="Deathstalker Vernon in Stillward Church (56.9, 39.4)" },
    { type="TURNIN", title="Vernon's Task", questId=40854, coords={ x=56.9, y=39.4 }, npc = { name="Deathstalker Vernon" }, note="Deathstalker Vernon in Stillward Church (56.9, 39.4)" },
    { type="TURNIN", title="Foulhide Mongrels", questId=40992, coords={ x=57.5, y=39.8 }, npc = { name="Harlan Ballow" }, note="Harlan Ballow in Stillward Church (57.5, 39.8)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
