-- =========================
-- QS_Badlands_40_41.lua
-- Converted from TourGuide format on 2025-08-17 18:59:06
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Badlands_40_41"] = {
  title    = "Badlands (40-41)",
  next     = "Swamp of Sorrows (41-42)",
  nextKey  = "QS_Swamp_of_Sorrows_41_42",
  faction  = "Horde",
  minLevel = 40,
  maxLevel = 41,
  steps = {
    { type="TRAVEL", coords={ x=64.0, y=36.0 }, note="Travel to Undercity (64.0, 36.0)" },
    { type="NOTE", note="Buy Frost Oil from Auction House. Skip this if not available. Don't buy if this is your first character and you still need to purchase a mount (64.0, 36.0)", coords={ x=64.0, y=36.0 } },
    { type="NOTE", note="Buy Gyrochronatom from Auction House. Don't buy if you didn't find a Frost Oil. Don't buy if this is your first character and you still need to purchase a mount (64.0, 36.0)", coords={ x=64.0, y=36.0 } },
    { type="NOTE", note="Buy Healing Potion from Auction House. Don't buy if you didn't find a Frost Oil and Gyrochronatom. Don't buy if this is your first character and you still need to purchase a mount (64.0, 36.0)", coords={ x=64.0, y=36.0 } },
    { type="NOTE", note="Buy Lesser Invisibility Potion from Auction House. Don't buy if you didn't find a Frost Oil and Gyrochronatom. Don't buy if this is your first character and you still need to purchase a mount (64.0, 36.0)", coords={ x=64.0, y=36.0 } },
    { type="NOTE", note="Buy 4 Buzzard Wing from Auction House - Skip this if not available (64.0, 36.0)", coords={ x=64.0, y=36.0 } },
    { type="NOTE", note="Withdraw Fizzle Brassbolts' Letter from the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="TRAVEL", coords={ x=45.4, y=96.6 }, note="Travel to Wetlands (45.4, 96.6)" },
    { type="TRAVEL", coords={ x=53.7, y=72.2 }, note="Travel to Loch Modan through the tunnel (53.7, 72.2) (55, 95)" },
    { type="TRAVEL", coords={ x=47.2, y=94.9 }, note="Travel to Badlands (47.2, 94.9)" },
    { type="TRAVEL", coords={ x=42.25, y=52.7 }, note="Travel to Valley of Fangs (42.25, 52.70)" },
    { type="TURNIN", title="Martek the Exiled", questId=1106, coords={ x=42.25, y=52.7 }, npc = { name="Martek" }, note="Martek the Exiled in Valley of Fangs (42.25, 52.70)" },
    { type="ACCEPT", title="Indurium", questId=1108, coords={ x=42.25, y=52.7 }, npc = { name="Martek" }, note="Martek the Exiled in Valley of Fangs (42.25, 52.70)" },
    { type="ACCEPT", title="Barbecued Buzzard Wings", questId=703, coords={ x=42.38, y=52.83 }, npc = { name="Rigglefuzz" }, note="Rigglefuzz in Valley of Fangs (42.38, 52.83)" },
    { type="COMPLETE", title="Indurium", questId=1108, coords={ x=49.97, y=68.31 }, note="Collect 10 Indurium Flake from Stonevault mobs in Agmond's End (49.97, 68.31)" },
    { type="TURNIN", title="Indurium", questId=1108, coords={ x=42.25, y=52.7 }, npc = { name="Martek" }, note="Martek the Exiled in Valley of Fangs (42.25, 52.70)" },
    { type="ACCEPT", title="News for Fizzle", questId=1137, coords={ x=42.25, y=52.7 }, npc = { name="Martek" }, note="Martek the Exiled in Valley of Fangs (42.25, 52.70)" },
    { type="TRAVEL", coords={ x=25.91, y=44.91 }, note="Travel to The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Study of the Elements: Rock", questId=710, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Coolant Heads Prevail", questId=713, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="TURNIN", title="Coolant Heads Prevail", questId=713, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Gyro... What?", questId=714, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="TURNIN", title="Gyro... What?", questId=714, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Liquid Stone", questId=715, coords={ x=25.83, y=44.29 }, npc = { name="Lucien Tosselwrench" }, note="Lucien Tosselwrench in The Dustbowl (25.83, 44.29)" },
    { type="TURNIN", title="Liquid Stone", questId=715, coords={ x=25.83, y=44.29 }, npc = { name="Lucien Tosselwrench" }, note="Lucien Tosselwrench in The Dustbowl (25.83, 44.29)" },
    { type="COMPLETE", title="Study of the Elements: Rock", questId=710, coords={ x=13.12, y=38.86 }, note="Kill the Lesser Rock Elemental and collect 10 Small Stone Shard. Make a start on this quest and skip it for now if you can't find any Lesser Rock Elemental (13.12, 38.86)" },
    { type="TRAVEL", coords={ x=4.0, y=44.9 }, note="Travel to Kargath (4, 44.9)" },
    { type="SET_HEARTH", title="Kargath", coords={ x=2.84, y=45.91 }, npc = { name="Innkeeper Shul'kar" }, note="Speak to Innkeeper Shul'kar and set hearth at Kargath (2.84, 45.91)" },
    { type="FLIGHTPATH", npc = { name="Gorrik" }, coords={ x=4.0, y=44.9 }, note="Speak to Gorrik and grab flight path for Kargath (4, 44.9)" },
    { type="ACCEPT", title="Coyote Thieves", questId=1419, coords={ x=6.5, y=47.1 }, npc = { name="Neeka Bloodscar" }, note="Neeka Bloodscar in Kargath (6.5, 47.1)" },
    { type="ACCEPT", title="Report to Helgrum", questId=1420, coords={ x=6.5, y=47.1 }, npc = { name="Neeka Bloodscar" }, note="Neeka Bloodscar in Kargath (6.5, 47.1)" },
    { type="ACCEPT", title="Broken Alliances", questId=782, coords={ x=2.9, y=45.8 }, npc = { name="Gorn" }, note="Gorn in Kargath in Kargath (2.9, 45.8)" },
    { type="ACCEPT", title="Badlands Reagent Run", questId=2258, coords={ x=2.5, y=46.1 }, npc = { name="Jarkal Mossmeld" }, note="Jarkal Mossmeld in Kargath (2.5, 46.1)" },
    { type="COMPLETE", title="Study of the Elements: Rock", questId=710, coords={ x=13.12, y=38.86 }, note="Kill the Lesser Rock Elemental and collect 10 Small Stone Shard (13.12, 38.86)" },
    { type="TURNIN", title="Study of the Elements: Rock", questId=710, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Study of the Elements: Rock", questId=711, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="COMPLETE", title="Study of the Elements: Rock", questId=711, coords={ x=15.52, y=32.18 }, note="Kill Rock Elemental until you've collected 3 Large Stone Slab. They are found either further West or to the South of Badlands (15.52, 32.18)" },
    { type="NOTE", note="Kill Rock Elementals to collect 5 Rock Elemental Shard (15.52, 32.18)", coords={ x=15.52, y=32.18 } },
    { type="TURNIN", title="Study of the Elements: Rock", questId=711, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="ACCEPT", title="Study of the Elements: Rock", questId=712, coords={ x=25.91, y=44.91 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl (25.91, 44.91)" },
    { type="NOTE", note="Kill any Coyotes for 30 Coyote Jawbone and 10 Crag Coyote Fang" },
    { type="COMPLETE", title="Barbecued Buzzard Wings", questId=703, coords={ x=15.1, y=59.84 }, note="Kill the Buzzards for 4 Buzzard Wing (15.10, 59.84)" },
    { type="NOTE", note="Kill any Buzzards and collect 5 Buzzard Gizzard in Apocryphan's Rest (15.10, 59.84)", coords={ x=15.1, y=59.84 } },
    { type="TRAVEL", coords={ x=17.03, y=84.4 }, note="Travel to Camp Cagg (17.03, 84.40)" },
    { type="COMPLETE", title="Study of the Elements: Rock", questId=712, coords={ x=17.03, y=84.4 }, note="Kill the Greater Rock Elemental and collect 5 Bracers of Rock Binding in Camp Cagg. Drop rate is high, avoid the level 44 Greater Rock Elemental (17.03, 84.40)" },
    { type="COMPLETE", title="Broken Alliances", questId=782, coords={ x=11.0, y=72.0 }, note="Kill Boss Tho'grun who patrol down to the southwest side of the zone and back in a circle. You should be able to pick Boss Tho'grun off the back of the pack easily (11, 72) (18, 79.7) (59, 69) (48, 51) (29.5, 59) (23, 52)" },
    { type="TRAVEL", coords={ x=13.0, y=36.0 }, note="Travel to Badlands (13, 36)" },
    { type="COMPLETE", title="Badlands Reagent Run", questId=2258, coords={ x=13.0, y=36.0 }, note="Kill Coyotes for 10 Crag Coyote Fang (13, 36) (14, 60) (11, 63)" },
    { type="COMPLETE", title="Coyote Thieves", questId=1419, coords={ x=20.09, y=51.1 }, note="Kill Coyotes for 30 Coyote Jawbone (20.09, 51.10) (29.91, 70.79) (42.01, 73.53)" },
    { type="TRAVEL", coords={ x=25.91, y=44.91 }, note="Travel to The Dustbowl (25.91, 44.91)" },
    { type="TURNIN", title="Study of the Elements: Rock", questId=712, coords={ x=25.9, y=45.0 }, npc = { name="Lotwil Veriatus" }, note="Lotwil Veriatus in The Dustbowl - Skip the follow-up (25.9, 45.0)" },
    { type="TRAVEL", coords={ x=25.9, y=45.0 }, note="Travel to Kargath (25.9, 45.0)" },
    { type="TURNIN", title="Coyote Thieves", questId=1419, coords={ x=6.5, y=47.1 }, npc = { name="Neeka Bloodscar" }, note="Neeka Bloodscar in Kargath (6.5, 47.1)" },
    { type="TURNIN", title="Broken Alliances", questId=782, coords={ x=2.9, y=45.8 }, npc = { name="Gorn" }, note="Gorn in Kargath (2.9, 45.8)" },
    { type="TURNIN", title="Badlands Reagent Run", questId=2258, coords={ x=2.5, y=46.1 }, npc = { name="Jarkal Mossmeld" }, note="Jarkal Mossmeld in Kargath (2.5, 46.1)" },
    { type="TRAVEL", coords={ x=42.38, y=52.83 }, note="Travel to Valley of Fangs (42.38, 52.83)" },
    { type="TURNIN", title="Barbecued Buzzard Wings", questId=703, coords={ x=42.38, y=52.83 }, npc = { name="Rigglefuzz" }, note="Rigglefuzz in Valley of Fangs (42.38, 52.83)" },
    { type="NOTE", note="Grom'gol Base Camp" },
    { type="TURNIN", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.7, y=10.5 }, note="Barnil Stonepot (35.7, 10.5)" },
    { type="ACCEPT", title="Nothing But The Truth", questId=1372, coords={ x=87.0, y=36.4 }, note="Apothecary Faustin (87.0, 36.4)" },
    { type="TURNIN", title="Nothing But The Truth", questId=1372, coords={ x=87.7, y=35.7 }, note="Deathstalker Zraedus (87.7, 35.7)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
