-- =========================
-- QS_Stranglethorn_42_43.lua
-- Converted from TourGuide format on 2025-08-17 18:59:06
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Stranglethorn_42_43"] = {
  title    = "Stranglethorn (42-43)",
  next     = "Dustwallow Marsh (43-44)",
  nextKey  = "QS_Dustwallow_Marsh_43_44",
  faction  = "Horde",
  minLevel = 42,
  maxLevel = 43,
  steps = {
    { type="TRAVEL", coords={ x=32.16, y=29.18 }, note="Travel to Grom'gol Base Camp (32.16, 29.18)" },
    { type="TURNIN", title="Mok'thardin's Enchantment", questId=571, coords={ x=32.16, y=29.18 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.16, 29.18)" },
    { type="ACCEPT", title="Mok'thardin's Enchantment", questId=573, coords={ x=32.16, y=29.18 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.16, 29.18)" },
    { type="TURNIN", title="Bloody Bone Necklaces", questId=596, coords={ x=32.23, y=27.77 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.23, 27.77)" },
    { type="ACCEPT", title="Split Bone Necklace", questId=598, coords={ x=32.21, y=27.74 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.21, 27.74)" },
    { type="TURNIN", title="Raptor Mastery", questId=196, coords={ x=35.65, y=10.75 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.75)" },
    { type="ACCEPT", title="Raptor Mastery", questId=197, coords={ x=35.65, y=10.75 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.65, 10.75)" },
    { type="TRAVEL", coords={ x=27.0, y=77.2 }, note="Travel to Booty Bay (27.0, 77.2)" },
    { type="TURNIN", title="Dream Dust in the Swamp", questId=1116, coords={ x=27.0, y=77.2 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern (27.0, 77.2)" },
    { type="ACCEPT", title="Tran'rek", questId=2864, coords={ x=27.0, y=77.2 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern, in second floor (27.0, 77.2)" },
    { type="ACCEPT", title="Rumors for Kravel", questId=1117, coords={ x=27.0, y=77.2 }, npc = { name="Krazek" }, note="Krazek in The Salty Sailor Tavern, in second floor (27.0, 77.2)" },
    { type="ACCEPT", title="Zanzil's Secret", questId=621, coords={ x=27.1, y=77.3 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.1, 77.3)" },
    { type="ACCEPT", title="Scaring Shaky", questId=606, coords={ x=27.79, y=77.08 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.79, 77.08)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=595, coords={ x=28.08, y=76.19 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.19)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=595, coords={ x=27.29, y=69.51 }, npc = { name="Bloodsail Correspondence" }, note="Bloodsail Correspondence in Southern Savage Coast, it's a parchment on top of a barrel (27.29, 69.51)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=597, coords={ x=27.29, y=69.51 }, npc = { name="Bloodsail Correspondence" }, note="Bloodsail Correspondence in Southern Savage Coast (27.29, 69.51)" },
    { type="COMPLETE", title="Scaring Shaky", questId=606, coords={ x=33.03, y=65.66 }, note="Kill Elder Mistvale Gorilla and collect 5 Mistvale Giblets in Mistvale Valley (33.03, 65.66)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=597, coords={ x=28.08, y=76.23 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.23)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=599, coords={ x=28.08, y=76.23 }, npc = { name="First Mate Crazz" }, note="First Mate Crazz in Booty Bay (28.08, 76.23)" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=599, coords={ x=27.17, y=76.98 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.17, 76.98)" },
    { type="ACCEPT", title="The Bloodsail Buccaneers", questId=604, coords={ x=27.1, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.1, 77.0)" },
    { type="TURNIN", title="Scaring Shaky", questId=606, coords={ x=27.79, y=77.08 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.79, 77.08)" },
    { type="ACCEPT", title="Return to MacKinley", questId=607, coords={ x=27.79, y=77.08 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.79, 77.08)" },
    { type="ACCEPT", title="Up to Snuff", questId=587, coords={ x=27.0, y=77.3 }, npc = { name="Deeg" }, note="Deeg in Booty Bay (27.0, 77.3)" },
    { type="SET_HEARTH", title="Booty Bay", coords={ x=27.1, y=77.3 }, npc = { name="Innkeeper Skindle" }, note="Speak to Innkeeper Skindle and set hearth at Booty Bay (27.1, 77.3)" },
    { type="ACCEPT", title="South Seas Delicacy", questId=60155, npc = { name="Innkeeper Skindle" }, note="Innkeeper Skindle" },
    { type="TURNIN", title="Singing Blue Shards", questId=605, coords={ x=27.11, y=77.21 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub, in The Salty Sailor Tavern (27.11, 77.21)" },
    { type="ACCEPT", title="Venture Company Mining", questId=600, coords={ x=27.1, y=77.3 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.1, 77.3)" },
    { type="ACCEPT", title="Akiris by the Bundle", questId=617, coords={ x=26.7, y=76.4 }, npc = { name="Privateer Bloads" }, note="Privateer Bloads in Booty Bay (26.7, 76.4)" },
    { type="NOTE", note="Store Bundle of Atal'ai Artifacts in the bank. Tick this step (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="Store Draenethyst Shard in the bank. Tick this step (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="Store Mire Lord Fungus in the bank. Tick this step (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="Store Shadow Panther Heart in the bank. Tick this step (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="TURNIN", title="Return to MacKinley", questId=607, coords={ x=27.79, y=77.08 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.79, 77.08)" },
    { type="ACCEPT", title="Voodoo Dues", questId=609, coords={ x=27.8, y=77.1 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.8, 77.1)" },
    { type="ACCEPT", title="Stoley's Debt", questId=2872, coords={ x=27.8, y=77.1 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay (27.8, 77.1)" },
    { type="ACCEPT", title="Keep An Eye Out", questId=576, coords={ x=28.6, y=75.8 }, npc = { name="Dizzy One-Eye" }, note="Dizzy One-Eye in Booty Bay (28.6, 75.8)" },
    { type="TRAVEL", coords={ x=30.85, y=72.37 }, note="Travel to Wild Shore (30.85, 72.37) (32.93, 74.27)" },
    { type="NOTE", note="Collect Bloodsail Charts on top the table in Wild Shore (26.9, 82.5)", coords={ x=26.9, y=82.5 } },
    { type="NOTE", note="Collect Bloodsail Orders on top of the crate in Wild Shore (27.8, 83.1)", coords={ x=27.8, y=83.1 } },
    { type="NOTE", note="Kill crabs for legs" },
    { type="COMPLETE", title="The Bloodsail Buccaneers", questId=604, coords={ x=30.31, y=80.75 }, note="Kill 10 Bloodsail Swashbuckler in Wild Shore (30.31, 80.75)" },
    { type="COMPLETE", title="Up to Snuff", questId=587, coords={ x=30.0, y=80.0 }, note="Kill Bloodsail pirates and collect 15 Snuff in Wild Shore (30, 80)" },
    { type="COMPLETE", title="Keep An Eye Out", questId=576, coords={ x=30.0, y=80.0 }, note="The Pirates should have dropped Dizzy's Eye by now, or else keep killing pirates until you find one (30, 80)" },
    { type="TRAVEL", coords={ x=27.1, y=77.3 }, note="Travel or Hearthstone to Booty Bay (27.1, 77.3)" },
    { type="TURNIN", title="Up to Snuff", questId=587, coords={ x=27.0, y=77.3 }, npc = { name="Deeg" }, note="Deeg in Booty Bay (27.0, 77.3)" },
    { type="TURNIN", title="South Seas Delicacy", questId=60155, npc = { name="Innkeeper Skindle" }, note="Innkeeper Skindle (27.1,77.3" },
    { type="TURNIN", title="The Bloodsail Buccaneers", questId=604, coords={ x=27.1, y=77.0 }, npc = { name="Fleet Master Seahorn" }, note="Fleet Master Seahorn in Booty Bay (27.1, 77.0)" },
    { type="TURNIN", title="Keep An Eye Out", questId=576, coords={ x=28.6, y=75.8 }, npc = { name="Dizzy One-Eye" }, note="Dizzy One-Eye in Booty Bay (28.6, 75.8)" },
    { type="TRAVEL", coords={ x=30.85, y=72.37 }, note="Travel to Southern Savage Coast (30.85, 72.37) (28.88, 58.10)" },
    { type="NOTE", note="Collect Holy Spring Water from the well by Nek'mani Wellspring fo (28, 61)", coords={ x=28.0, y=61.0 } },
    { type="COMPLETE", title="Akiris by the Bundle", questId=617, coords={ x=25.72, y=61.2 }, note="Kill the Naga at the Nek'mani Wellspring for 10 Akiris Reed (25.72, 61.20)" },
    { type="COMPLETE", title="Naga Tridents", questId=60481, coords={ x=25.72, y=61.2 }, note="Kill the Naga at for 14 Tridents (25.72, 61.20)" },
    { type="COMPLETE", title="Mok'thardin's Enchantment", questId=573, coords={ x=25.72, y=61.2 }, note="Kill 10 Naga Explorer at the Nek'mani Wellspring (25.72, 61.20)" },
    { type="TRAVEL", coords={ x=27.16, y=58.98 }, note="Travel to Ruins of Jubuwal (27.16, 58.98) (29.81, 56.60)(30.88, 53.61) (34.75, 51.82)" },
    { type="NOTE", note="Collect 12 Zanzil's Mixture drop from any Zanzil mobs" },
    { type="COMPLETE", title="Jon-Jon the Crow", questId=609, coords={ x=34.75, y=51.82 }, note="Kill Jon-Jon the Crow and collect Jon-Jon's Golden Spyglass in Ruins of Jubuwal (34.75, 51.82) | Kill Maury \\Club Foot\\ Wilkins and collect Maury's Clubbed Foot in Ruins of Jubuwal (35.18, 51.11)" },
    { type="TRAVEL", coords={ x=33.9, y=54.0 }, note="Travel to Ruins of Aboraz (33.90, 54.00) (38.34, 56.71)" },
    { type="COMPLETE", title="Chucky \\Ten Thumbs\\", questId=609, coords={ x=40.05, y=58.21 }, note="Kill Maury \\Club Foot\\ Wilkins and collect Chucky's Huge Ring in Ruins of Aboraz (40.05, 58.21)" },
    { type="COMPLETE", title="Zanzil's Secret", questId=621, coords={ x=40.0, y=57.0 }, note="Kill Zanzil Hunter and Zanzil Zombie at the Ruins of Aboraz for 12 Zanzil's Mixture (40, 57)" },
    { type="TRAVEL", note="Travel to Stranglethorn Vale" },
    { type="COMPLETE", title="Venture Company Mining", questId=600, coords={ x=40.14, y=42.57 }, note="Kill the Venture Co. goblins for 10 Singing Blue Crystal (40.14, 42.57) (41.72, 44.57)" },
    { type="TRAVEL", note="Travel to Stranglethorn Vale" },
    { type="COMPLETE", title="Raptor Mastery", questId=197, coords={ x=28.0, y=44.0 }, note="Kill Tethis and loot Talon of Tethis (28, 44)" },
    { type="TRAVEL", coords={ x=27.1, y=77.3 }, note="Travel or Hearthstone to Booty Bay (27.1, 77.3)" },
    { type="TURNIN", title="Venture Company Mining", questId=600, coords={ x=27.1, y=77.3 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.1, 77.3)" },
    { type="TURNIN", title="Zanzil's Secret", questId=621, coords={ x=27.1, y=77.3 }, npc = { name="Crank Fizzlebub" }, note="Crank Fizzlebub in The Salty Sailor Tavern (27.1, 77.3)" },
    { type="TURNIN", title="Akiris by the Bundle", questId=617, coords={ x=26.7, y=76.4 }, npc = { name="Privateer Bloads" }, note="Privateer Bloads in Booty Bay (26.7, 76.4)" },
    { type="TURNIN", title="Voodoo Dues", questId=609, coords={ x=27.8, y=77.1 }, npc = { name="MacKinley" }, note="\\Sea Wolf\\ MacKinley in Booty Bay - Skip follow up (27.8, 77.1)" },
    { type="NOTE", note="Store Nimboya's Pike in the bank. Tick this step (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="Store Goblin Rumors in the bank. Tick this step (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 1. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 4. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 6. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 8. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 10. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 11. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 14. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 16. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 18. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 20. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 21. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 24. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 25. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 26. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="NOTE", note="You should have most of the Chapters for 'The Green Hills of Stranglethorn' by now, but you still need Green Hills of Stranglethorn - Page 27. Try to purchase from the auction house Auctioneer O'reely in Booty Bay, sell extras or trade with other players in general chat. Tick this step to skip (26.6, 76.4)", coords={ x=26.6, y=76.4 } },
    { type="TRAVEL", coords={ x=32.21, y=27.75 }, note="Travel to Grom'gol Base Camp (32.21, 27.75)" },
    { type="TURNIN", title="Mok'thardin's Enchantment", questId=573, coords={ x=32.08, y=29.26 }, npc = { name="Far Seer Mok'thardin" }, note="Far Seer Mok'thardin in Grom'gol Base Camp (32.08, 29.26)" },
    { type="TRAVEL", coords={ x=35.7, y=10.8 }, note="Travel to Nesingwary's Expedition (35.7, 10.8)" },
    { type="TURNIN", title="Raptor Mastery", questId=197, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="ACCEPT", title="Big Game Hunter", questId=208, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="COMPLETE", title="Big Game Hunter", questId=208, coords={ x=38.0, y=35.0 }, note="Kill King Bangalash and loot the Head of Bangalash (38, 35)" },
    { type="ACCEPT", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter I", questId=339, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter II", questId=340, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter III", questId=341, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="ACCEPT", title="Chapter IV", questId=342, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter I", questId=339, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter II", questId=340, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter III", questId=341, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="Chapter IV", questId=342, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="TURNIN", title="The Green Hills of Stranglethorn", questId=338, coords={ x=35.65, y=10.51 }, npc = { name="Barnil Stonepot" }, note="Barnil Stonepot in Nesingwary's Expedition (35.65, 10.51)" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="NOTE", note="Abandon The Green Hills of Stranglethorn and Chapter quest if you're unable to complete it now. You can complete this later" },
    { type="TRAVEL", coords={ x=45.42, y=30.46 }, note="Travel to Stranglethorn Vale (45.42, 30.46)" },
    { type="COMPLETE", title="Split Bone Necklace", questId=598, coords={ x=42.55, y=35.34 }, note="Kill Skullsplitter trolls in Ziata'jai Ruins and Balia'mah Ruins (42.55, 35.34) (45.42, 30.46)" },
    { type="TRAVEL", coords={ x=35.7, y=10.8 }, note="Travel to Nesingwary's Expedition (35.7, 10.8)" },
    { type="TURNIN", title="Big Game Hunter", questId=208, coords={ x=35.7, y=10.8 }, npc = { name="Hemet Nesingwary" }, note="Hemet Nesingwary in Nesingwary's Expedition (35.7, 10.8)" },
    { type="TRAVEL", coords={ x=32.21, y=27.75 }, note="Travel to Grom'gol Base Camp (32.21, 27.75)" },
    { type="TURNIN", title="Split Bone Necklace", questId=598, coords={ x=32.21, y=27.75 }, npc = { name="Kin'weelay" }, note="Kin'weelay in Grom'gol Base Camp (32.21, 27.75)" },
    { type="ACCEPT", title="Grim Message", questId=2932, coords={ x=32.16, y=27.77 }, npc = { name="Nimboya" }, note="Nimboya in Grom'gol Base Camp (32.16, 27.77)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
