-- =========================
-- QS_Western_Plaguelands_56_56.lua
-- Converted from TourGuide format on 2025-08-17 18:59:07
-- =========================

QuestShellGuides = QuestShellGuides or {}

QuestShellGuides["QS_Western_Plaguelands_56_56"] = {
  title    = "Western Plaguelands (56-56)",
  next     = "Eastern Plaguelands (56-57)",
  nextKey  = "QS_Eastern_Plaguelands_56_57",
  faction  = "Horde",
  minLevel = 56,
  maxLevel = 56,
  steps = {
    { type="TRAVEL", coords={ x=67.74, y=37.91 }, note="Travel to Undercity (67.74, 37.91)" },
    { type="SET_HEARTH", title="Undercity", coords={ x=67.74, y=37.91 }, npc = { name="Innkeeper Norman" }, note="Speak to Innkeeper Norman and set hearth at Undercity (67.74, 37.91)" },
    { type="ACCEPT", title="The New Frontier", questId=1004, coords={ x=63.9, y=43.76 }, npc = { name="Harbinger Balthazad" }, note="Harbinger Balthazad in Trade Quarter (63.90, 43.76)" },
    { type="ACCEPT", title="A Call to Arms: The Plaguelands!", questId=5094, coords={ x=63.9, y=43.76 }, npc = { name="Harbinger Balthazad" }, note="Harbinger Balthazad in Trade Quarter (63.90, 43.76)" },
    { type="NOTE", note="Withdraw Felwood Slime Sample from the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Withdraw Un'Goro Slime Sample from the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Withdraw Everlook Report from the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Withdraw Studies in Spirit Speaking from the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Store Cenarion Beacon in the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Store Corrupted Soul Shard in the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="NOTE", note="Store Cenarion Plant Salve in the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="TURNIN", title="A Donation of Runecloth", questId=7818, coords={ x=71.83, y=29.15 }, npc = { name="Ralston Farnsley" }, note="Ralston Farnsley in Magic Quarter (71.83, 29.15)" },
    { type="TURNIN", title="A Donation of Mageweave", questId=7817, coords={ x=71.83, y=29.15 }, npc = { name="Ralston Farnsley" }, note="Ralston Farnsley in Magic Quarter (71.83, 29.15)" },
    { type="TRAVEL", coords={ x=52.94, y=77.23 }, note="Travel to The Apothecarium (52.94, 77.23)" },
    { type="NOTE", note="Click on the Testing Equipment and turn in the quest to get a Un'Goro Tested Sample, you will need to open it to get Pure Un'Goro Sample, keep turning in the quest and check the item until you run out of Un'Goro Slime Sample (47.56, 73.40)", coords={ x=47.56, y=73.4 } },
    { type="COMPLETE", title="... and a Batch of Ooze", questId=4294, coords={ x=47.56, y=73.4 }, note="Get 5 Pure Un'Goro Sample from the Testing Equipment (47.56, 73.40)" },
    { type="TURNIN", title="... and a Batch of Ooze", questId=4294, coords={ x=47.56, y=73.4 }, npc = { name="Chemist Fuely" }, note="Chemist Fuely in The Apothecarium (47.56, 73.40)" },
    { type="NOTE", note="Click on the Testing Equipment and turn in the quest to get a Corrupt Tested Sample, you will need to open it to get Pure Un'Goro Sample, keep turning in the quest and check the item until you run out of Felwood Slime Sample (47.56, 73.40)", coords={ x=47.56, y=73.4 } },
    { type="COMPLETE", title="A Sample of Slime...", questId=4293, coords={ x=47.81, y=73.17 }, note="Get 5 Corrupted Felwood Sample from the Testing Equipment (47.81, 73.17)" },
    { type="TURNIN", title="A Sample of Slime...", questId=4293, coords={ x=47.53, y=73.26 }, npc = { name="Chemist Fuely" }, note="Chemist Fuely in The Apothecarium (47.53, 73.26)" },
    { type="ACCEPT", title="Melding of Influences", questId=4642, coords={ x=47.84, y=73.16 }, npc = { name="Chemist Fuely" }, note="Chemist Fuely in The Apothecarium (47.84, 73.16)" },
    { type="NOTE", note="Store Encased Corrupt Ooze in the bank (66.0, 45.2)", coords={ x=66.0, y=45.2 } },
    { type="TRAVEL", coords={ x=83.14, y=68.92 }, note="Travel to The Bulwark (83.14, 68.92)" },
    { type="TURNIN", title="A Call to Arms: The Plaguelands!", questId=5094, coords={ x=83.14, y=68.92 }, npc = { name="High Executor Derrington" }, note="High Executor Derrington in The Bulwark (83.14, 68.92)" },
    { type="ACCEPT", title="Scarlet Diversions", questId=5096, coords={ x=83.14, y=68.92 }, npc = { name="High Executor Derrington" }, note="High Executor Derrington in The Bulwark (83.14, 68.92)" },
    { type="NOTE", note="Collect Flame in a Bottle from the Box of Incendiaries in The Bulwark (83.18, 69.05)", coords={ x=83.18, y=69.05 } },
    { type="TURNIN", title="The Everlook Report", questId=6029, coords={ x=83.19, y=68.43 }, npc = { name="Argent Officer Garush" }, note="Argent Officer Garush in The Bulwark (83.19, 68.43)" },
    { type="TURNIN", title="Argent Dawn Commission", questId=5405, coords={ x=83.19, y=68.43 }, npc = { name="Argent Officer Garush" }, note="Argent Officer Garush in The Bulwark (83.19, 68.43)" },
    { type="NOTE", note="Equip Argent Dawn Commission, you will need this equipped to collect Scourgestones that you can turn in for Argent Dawn reputation" },
    { type="ACCEPT", title="A Plague Upon Thee", questId=5901, coords={ x=83.28, y=72.36 }, npc = { name="Mickey Levine" }, note="Mickey Levine in The Bulwark (83.28, 72.36)" },
    { type="TRAVEL", coords={ x=38.41, y=54.06 }, note="Travel to Felstone Field (38.41, 54.06)" },
    { type="ACCEPT", title="Better Late Than Never", questId=5021, coords={ x=38.41, y=54.06 }, npc = { name="Janice Felstone" }, note="Janice Felstone in Felstone Field, upstairs in the inn (38.41, 54.06)" },
    { type="TURNIN", title="Better Late Than Never", questId=5021, coords={ x=38.72, y=55.25 }, npc = { name="Janice's Parcel" }, note="Janice's Parcel in the barn nextdoor (38.72, 55.25)" },
    { type="ACCEPT", title="Better Late Than Never", questId=5023, coords={ x=38.72, y=55.25 }, npc = { name="Janice's Parcel" }, note="Janice's Parcel in Felstone Field (38.72, 55.25)" },
    { type="COMPLETE", title="Scarlet Diversions", questId=5096, itemId=12807, coords={ x=40.55, y=51.95 }, note="Click on the command tent to set it on fire and use the Scourge Banner next to it in Felstone Field (40.55, 51.95)" },
    { type="TURNIN", title="Scarlet Diversions", questId=5096, coords={ x=83.19, y=68.92 }, npc = { name="High Executor Derrington" }, note="High Executor Derrington in The Bulwark (83.19, 68.92)" },
    { type="ACCEPT", title="The Scourge Cauldrons", questId=5228, coords={ x=83.14, y=68.97 }, npc = { name="High Executor Derrington" }, note="High Executor Derrington in The Bulwark (83.14, 68.97)" },
    { type="TURNIN", title="The Scourge Cauldrons", questId=5228, coords={ x=83.04, y=71.93 }, npc = { name="Shadow Priestess Vandis" }, note="Shadow Priestess Vandis in The Bulwark (83.04, 71.93)" },
    { type="ACCEPT", title="Target: Felstone Field", questId=5229, coords={ x=83.04, y=71.93 }, npc = { name="Shadow Priestess Vandis" }, note="Shadow Priestess Vandis in The Bulwark (83.04, 71.93)" },
    { type="COMPLETE", title="Target: Felstone Field", questId=5229, coords={ x=37.13, y=57.13 }, note="Kill Cauldron Lord Bilemaw and collect Felstone Field Cauldron Key in Felstone Field (37.13, 57.13)" },
    { type="TURNIN", title="Target: Felstone Field", questId=5229, coords={ x=37.19, y=56.92 }, npc = { name="Scourge Cauldron" }, note="Scourge Cauldron in Felstone Field (37.19, 56.92)" },
    { type="ACCEPT", title="Return to the Bulwark", questId=5230, coords={ x=37.17, y=56.99 }, npc = { name="Scourge Cauldron" }, note="Scourge Cauldron in Felstone Field (37.17, 56.99)" },
    { type="TRAVEL", coords={ x=83.03, y=71.92 }, note="Travel to The Bulwark (83.03, 71.92)" },
    { type="TURNIN", title="Return to the Bulwark", questId=5230, coords={ x=83.04, y=71.91 }, npc = { name="Shadow Priestess Vandis" }, note="Shadow Priestess Vandis in The Bulwark (83.04, 71.91)" },
    { type="ACCEPT", title="Target: Dalson's Tears", questId=5231, coords={ x=82.96, y=71.82 }, npc = { name="Shadow Priestess Vandis" }, note="Shadow Priestess Vandis in The Bulwark (82.96, 71.82)" },
    { type="TRAVEL", coords={ x=47.8, y=50.7 }, note="Travel to Dalson's Tears (47.8, 50.7)" },
    { type="NOTE", note="Collect 30 Bone Fragments for a later quest from the Skeletons" },
    { type="TURNIN", title="Mrs. Dalson's Diary", questId=5058, coords={ x=47.8, y=50.7 }, npc = { name="Dalson's Diary" }, note="Mrs. Dalson's Diary in Dalson's Tears, inside the barn on the floor (47.8, 50.7)" },
    { type="COMPLETE", title="Wandering Skeleton", questId=5060, coords={ x=47.66, y=50.08 }, note="Kill Wandering Skeleton, it should spawn outside the barn after you turn in 'Mrs. Dalson's Diary' and collect the Dalson Outhouse Key (47.66, 50.08)" },
    { type="TURNIN", title="Locked Away", questId=5059, coords={ x=48.11, y=49.66 }, npc = { name="Outhouse" }, note="Outhouse in Dalson's Tears (48.11, 49.66)" },
    { type="COMPLETE", title="Farmer Dalson", questId=5060, coords={ x=48.11, y=49.66 }, note="Kill Farmer Dalson, he should spawn after turn in 'Locked Away' from the outhouse and (48.11, 49.66)" },
    { type="TURNIN", title="Locked Away", questId=5060, coords={ x=47.39, y=49.62 }, npc = { name="Locked Cabinet" }, note="Locked Cabinet in Dalson's Tears, upstairs in the house (47.39, 49.62)" },
    { type="COMPLETE", title="Target: Dalson's Tears", questId=5231, coords={ x=45.97, y=52.46 }, note="Kill Cauldron Lord Malvinious and collect Dalson's Tears Cauldron Key in Dalson's Tears (45.97, 52.46)" },
    { type="TURNIN", title="Target: Dalson's Tears", questId=5231, coords={ x=46.15, y=52.06 }, npc = { name="Scourge Cauldron" }, note="Scourge Cauldron in Dalson's Tears (46.15, 52.06)" },
    { type="ACCEPT", title="Return to the Bulwark", questId=5232, coords={ x=46.15, y=52.06 }, npc = { name="Scourge Cauldron" }, note="Scourge Cauldron in Dalson's Tears (46.15, 52.06)" },
    { type="TRAVEL", coords={ x=83.03, y=71.92 }, note="Travel to The Bulwark (83.03, 71.92)" },
    { type="TURNIN", title="Return to the Bulwark", questId=5232, coords={ x=83.03, y=71.92 }, npc = { name="Shadow Priestess Vandis" }, note="Shadow Priestess Vandis in The Bulwark (83.03, 71.92)" },
    { type="ACCEPT", title="Target: Writhing Haunt", questId=5233, coords={ x=83.03, y=71.92 }, npc = { name="Shadow Priestess Vandis" }, note="Shadow Priestess Vandis in The Bulwark (83.03, 71.92)" },
    { type="TRAVEL", coords={ x=53.01, y=66.03 }, note="Travel to The Writhing Haunt (53.01, 66.03)" },
    { type="NOTE", note="Collect 30 Bone Fragments for a later quest from the Skeletons" },
    { type="ACCEPT", title="The Wildlife Suffers Too", questId=4984, coords={ x=53.67, y=64.76 }, npc = { name="Mulgris Deepriver" }, note="Mulgris Deepriver in The Writhing Haunt (53.67, 64.76)" },
    { type="COMPLETE", title="Target: Writhing Haunt", questId=5233, coords={ x=53.01, y=66.03 }, note="Kill Cauldron Lord Razarch and collect Writhing Haunt Cauldron Key in The Writhing Haunt (53.01, 66.03)" },
    { type="TURNIN", title="Target: Writhing Haunt", questId=5233, coords={ x=53.02, y=65.82 }, npc = { name="Scourge Cauldron" }, note="Scourge Cauldron in The Writhing Haunt (53.02, 65.82)" },
    { type="ACCEPT", title="Return to the Bulwark", questId=5234, coords={ x=53.02, y=65.82 }, npc = { name="Scourge Cauldron" }, note="Scourge Cauldron in The Writhing Haunt (53.02, 65.82)" },
    { type="TRAVEL", coords={ x=83.03, y=71.92 }, note="Travel to The Bulwark (83.03, 71.92)" },
    { type="TURNIN", title="Return to the Bulwark", questId=5234, coords={ x=83.03, y=71.9 }, npc = { name="Shadow Priestess Vandis" }, note="Shadow Priestess Vandis in The Bulwark (83.03, 71.90)" },
    { type="ACCEPT", title="Target: Gahrron's Withering", questId=5235, coords={ x=83.03, y=71.9 }, npc = { name="Shadow Priestess Vandis" }, note="Shadow Priestess Vandis in The Bulwark (83.03, 71.90)" },
    { type="TRAVEL", coords={ x=62.66, y=58.78 }, note="Travel to Gahrron's Withering (62.66, 58.78)" },
    { type="NOTE", note="Collect 30 Bone Fragments for a later quest from the Skeletons" },
    { type="COMPLETE", title="Target: Gahrron's Withering", questId=5235, coords={ x=62.66, y=58.78 }, note="Kill Cauldron Lord Soulwrath and collect Gahrron's Withering Cauldron Key in Gahrron's Withering (62.66, 58.78)" },
    { type="TURNIN", title="Target: Gahrron's Withering", questId=5235, coords={ x=62.57, y=58.65 }, npc = { name="Scourge Cauldron" }, note="Scourge Cauldron in Gahrron's Withering (62.57, 58.65)" },
    { type="ACCEPT", title="Return to the Bulwark", questId=5236, coords={ x=62.57, y=58.65 }, npc = { name="Scourge Cauldron" }, note="Scourge Cauldron in Gahrron's Withering (62.57, 58.65)" },
    { type="TRAVEL", coords={ x=66.58, y=39.76 }, note="Travel east to Eastern Plaguelands (66.58, 39.76) (67.12, 37.67)" },
    { type="NOTE", note="Tick to continue to the next guide" },
  }
}
